## Print function & display Function

In [1]:
from IPython.display import display

In [2]:
# Format of print function
print()

# Format of display function
display()

In [3]:
print("Fastest Indians to 8 ODI centuries ft....")

Fastest Indians to 8 ODI centuries ft....

In [4]:
display("Fastest Indians to 8 ODI centuries ft. ...")

'Fastest Indians to 8 ODI centuries ft. ...'

In [5]:
print(373773)

373773

In [6]:
print(38848.9992)

38848.9992

In [9]:
! pip install pandas

^C

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import pandas as pd

dictionary = {"A": [1, 2, 3, 4], "B": [22, 44, 66, 88] }

dataframe = pd.DataFrame(dictionary)
dataframe

   A   B
0  1  22
1  2  44
2  3  66
3  4  88

In [12]:
print(dataframe)

   A   B
0  1  22
1  2  44
2  3  66
3  4  88

In [13]:
display(dataframe)

   A   B
0  1  22
1  2  44
2  3  66
3  4  88

### Uses of print function