### Dictinary in Python

In [ ]:
# string : Immutable, ordered, duplicates are allowed
# list : Mutable, ordered, duplicates are allowed
# tuple : Immutable, ordered, duplicates are allowed
# set : Mutable, unordered, duplicates are not allowed
# frozenset : Immutable, unordered, duplicates are not allowed
# dict : Mutable, unordered, duplicates are not allowed, key-value pairs

In [ ]:
list1 = [1, 2, 3, 4, 5]
set1 = {1, 2, 3, 4, 5}
dict1 = {'a': 1, 'b': 2, 'c': 3}
frozenset1 = frozenset({1, 2, 3, 4, 5})
tuple1 = (1, 2, 3, 4, 5)
string1 = "Hello World"

In [4]:
dict1 = {}
dict1
type(dict1)

dict

In [3]:
dict1 = {'a': 1, 'b': 2, 'c': 3}
dict1

{'a': 1, 'b': 2, 'c': 3}

In [6]:
d1 = {"name": "John", "age": 30, "city": "New York"}

print(type(d1))  # <class 'dict'>
print(d1)
print(len(d1))

<class 'dict'>
{'name': 'John', 'age': 30, 'city': 'New York'}
3

In [7]:
d1 = {"name": "John", "age": 30, "city": "New York", "name": "John"}
d1

{'name': 'John', 'age': 30, 'city': 'New York'}

In [8]:
d1[0]

KeyError: 0

#### How to access items in dictionary

In [8]:
emp = {
    "name": "John",
    "age": 30,
    "city": "New York",
    "salary": 50000,
    "department": "IT"
}

emp

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'salary': 50000,
 'department': 'IT'}

In [9]:
emp["name"]

'John'

In [ ]:
emp[0] # error

In [13]:
emp["department"]

'IT'

In [12]:
# how can I get the city of john
emp["city"]  # New York

'New York'

In [11]:
emp["name"]

'John'

In [10]:
emp["salary"]

50000

In [63]:
for i in emp.keys():
    print(i)

name
age
city
salary
department

- get function

In [ ]:
# get the keys of the dictionary
# get function will check if the key is present in the dictionary or not
emp.keys()

In [21]:
emp.keys()

dict_keys(['name', 'age', 'city', 'salary', 'department'])

In [22]:
emp.values()

dict_values(['John', 30, 'New York', 50000, 'IT'])

In [23]:
emp.items()

dict_items([('name', 'John'), ('age', 30), ('city', 'New York'), ('salary', 50000), ('department', 'IT')])

In [15]:
emp = {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"}
emp

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'salary': 50000,
 'department': 'IT'}

In [16]:
emp.get("name")  # John

'John'

In [17]:
emp.get("department")  # IT

'IT'

In [18]:
# output should be "50000"
emp.get("salary")  # 50000

50000

In [19]:
emp.get("age")

30

In [20]:
emp.get(30)

In [10]:
pol = {"modi": "PM", "yogi": "CM", "rajnath": "Home Minister", "yashwant": "Finance Minister"}
pol

{'modi': 'PM',
 'yogi': 'CM',
 'rajnath': 'Home Minister',
 'yashwant': 'Finance Minister'}

In [26]:
pol.keys()

dict_keys(['modi', 'yogi', 'rajnath', 'yashwant'])

In [27]:
pol.values()

dict_values(['PM', 'CM', 'Home Minister', 'Finance Minister'])

In [28]:
pol.items()

dict_items([('modi', 'PM'), ('yogi', 'CM'), ('rajnath', 'Home Minister'), ('yashwant', 'Finance Minister')])

In [ ]:
pol["yashwant"] = "CM"

In [30]:
pol

{'modi': 'PM', 'yogi': 'CM', 'rajnath': 'Home Minister', 'yashwant': 'CM'}

In [31]:
pol["modi"] = "PM of India"
pol

{'modi': 'PM of India',
 'yogi': 'CM',
 'rajnath': 'Home Minister',
 'yashwant': 'CM'}

In [32]:
# change CM value of yogi to "CM of UP"
pol["yogi"] = "CM of UP"
pol

{'modi': 'PM of India',
 'yogi': 'CM of UP',
 'rajnath': 'Home Minister',
 'yashwant': 'CM'}

In [33]:
pol

{'modi': 'PM of India',
 'yogi': 'CM of UP',
 'rajnath': 'Home Minister',
 'yashwant': 'CM'}

In [34]:
for i in pol:
    print(i, pol[i])

modi PM of India
yogi CM of UP
rajnath Home Minister
yashwant CM

In [12]:
pol = {"modi": "PM", "yogi": "CM", "rajnath": "Home Minister", "yashwant": "Finance Minister"}
pol

{'modi': 'PM',
 'yogi': 'CM',
 'rajnath': 'Home Minister',
 'yashwant': 'Finance Minister'}

In [13]:
for i in pol.values():
    print(i)

PM
CM
Home Minister
Finance Minister

In [37]:
for i in pol.keys():
    print(i)

modi
yogi
rajnath
yashwant

In [38]:
for i in pol.items():
    print(i)

('modi', 'PM of India')
('yogi', 'CM of UP')
('rajnath', 'Home Minister')
('yashwant', 'CM')

### How we can change the items in the dictionary

In [41]:
mobile_brands = {"samsung": "Galaxy", "apple": "iPhone", "nokia": "Lumia", "oneplus": "Nord"}
mobile_brands

{'samsung': 'Galaxy', 'apple': 'iPhone', 'nokia': 'Lumia', 'oneplus': 'Nord'}

In [43]:
mobile_brands["samsung"] = "S25"
mobile_brands

{'samsung': 'S25', 'apple': 'iPhone', 'nokia': 'Lumia', 'oneplus': 'Nord'}

#### How to update the values using UPDATE function

In [67]:
emp1 = {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"}

new_data = { "emp_id": 101, "emp_name": "John", "emp_salary": 50000, "emp_department": "IT"}

empl = {"name2": "max"}
emp1.update(new_data)
emp1

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'salary': 50000,
 'department': 'IT',
 'emp_id': 101,
 'emp_name': 'John',
 'emp_salary': 50000,
 'emp_department': 'IT'}

In [14]:
dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'d': 4, 'e': 5, 'f': 6}
dict1.update(dict2)
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}

- Setdefault()

In [15]:
emp1 = {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"}
emp1.setdefault("name", "John")
emp1

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'salary': 50000,
 'department': 'IT'}

In [ ]:
emp1 = {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"}
emp1.setdefault("name")

'John'

In [46]:
emp1 = {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"}
emp1.setdefault("id", 101)
emp1

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'salary': 50000,
 'department': 'IT',
 'id': 101}

In [47]:
emp1 = {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"}
emp1.setdefault("passbook")
emp1

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'salary': 50000,
 'department': 'IT',
 'passbook': None}

### Remove items from dictionary

- pop

In [48]:
new_dict = {"jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6, "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12}
new_dict

{'jan': 1,
 'feb': 2,
 'mar': 3,
 'apr': 4,
 'may': 5,
 'jun': 6,
 'jul': 7,
 'aug': 8,
 'sep': 9,
 'oct': 10,
 'nov': 11,
 'dec': 12}

In [49]:
new_dict.pop("apr")
new_dict

{'jan': 1,
 'feb': 2,
 'mar': 3,
 'may': 5,
 'jun': 6,
 'jul': 7,
 'aug': 8,
 'sep': 9,
 'oct': 10,
 'nov': 11,
 'dec': 12}

In [50]:
new_dict.pop()
new_dict

TypeError: pop expected at least 1 argument, got 0

- popitem()

In [34]:
new_dict_crickers = {"sachin": 200, "dhoni": 50, "kohli": 75, "rohit": 80, "sehwag": 200}
new_dict_crickers

{'sachin': 200, 'dhoni': 50, 'kohli': 75, 'rohit': 80, 'sehwag': 200}

In [23]:
new_dict_crickers.popitem()
new_dict_crickers

{'sachin': 200, 'dhoni': 50, 'kohli': 75, 'rohit': 80}

In [61]:
new_dict_crickers.popitem("sachin")
new_dict_crickers

TypeError: dict.popitem() takes no arguments (1 given)

- Clear

In [35]:
new_dict_crickers = {"sachin": 200, "dhoni": 50, "kohli": 75, "rohit": 80, "sehwag": 200}
new_dict_crickers

{'sachin': 200, 'dhoni': 50, 'kohli': 75, 'rohit': 80, 'sehwag': 200}

In [31]:
new_dict_crickers.clear()

In [32]:
new_dict_crickers

{}

- Del

In [36]:
new_dict_crickers = {"sachin": 200, "dhoni": 50, "kohli": 75, "rohit": 80, "sehwag": 200}
new_dict_crickers

{'sachin': 200, 'dhoni': 50, 'kohli': 75, 'rohit': 80, 'sehwag': 200}

In [38]:
del new_dict_crickers["rohit"]

In [39]:
new_dict_crickers

{'sachin': 200, 'dhoni': 50, 'kohli': 75, 'sehwag': 200}

In [40]:
del new_dict_crickers

In [41]:
new_dict_crickers

NameError: name 'new_dict_crickers' is not defined

- NESTED Dictionary

In [43]:
# nested dictionary

new_dict = {"empid-01": {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"},
            "empid-02": {"name": "Jane", "age": 25, "city": "Los Angeles", "salary": 60000, "department": "HR"},
            "empid-03": {"name": "Mike", "age": 35, "city": "Chicago", "salary": 70000, "department": "Finance"}}
new_dict

{'empid-01': {'name': 'John',
  'age': 30,
  'city': 'New York',
  'salary': 50000,
  'department': 'IT'},
 'empid-02': {'name': 'Jane',
  'age': 25,
  'city': 'Los Angeles',
  'salary': 60000,
  'department': 'HR'},
 'empid-03': {'name': 'Mike',
  'age': 35,
  'city': 'Chicago',
  'salary': 70000,
  'department': 'Finance'}}

In [49]:
# WAP to get the salary of Jane? 
new_dict["empid-02"]["salary"]

60000

In [46]:
new_dict["empid-01"]["name"]

'John'

In [48]:
S = new_dict["empid-01"]
S["name"]

'John'

In [44]:
new_dict["empid-01"]

{'name': 'John',
 'age': 30,
 'city': 'New York',
 'salary': 50000,
 'department': 'IT'}

In [45]:
new_dict["empid-02"]

{'name': 'Jane',
 'age': 25,
 'city': 'Los Angeles',
 'salary': 60000,
 'department': 'HR'}

In [51]:
# How to make dataframe from nested list

# nested dictionary

new_dict = {"empid-01": {"name": "John", "age": 30, "city": "New York", "salary": 50000, "department": "IT"},
            "empid-02": {"name": "Jane", "age": 25, "city": "Los Angeles", "salary": 60000, "department": "HR"},
            "empid-03": {"name": "Mike", "age": 35, "city": "Chicago", "salary": 70000, "department": "Finance"}}
new_dict

{'empid-01': {'name': 'John',
  'age': 30,
  'city': 'New York',
  'salary': 50000,
  'department': 'IT'},
 'empid-02': {'name': 'Jane',
  'age': 25,
  'city': 'Los Angeles',
  'salary': 60000,
  'department': 'HR'},
 'empid-03': {'name': 'Mike',
  'age': 35,
  'city': 'Chicago',
  'salary': 70000,
  'department': 'Finance'}}

In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd

df = pd.DataFrame(new_dict)
df # T transpose

            empid-01     empid-02 empid-03
name            John         Jane     Mike
age               30           25       35
city        New York  Los Angeles  Chicago
salary         50000        60000    70000
department        IT           HR  Finance

In [54]:
df.T

          name age         city salary department
empid-01  John  30     New York  50000         IT
empid-02  Jane  25  Los Angeles  60000         HR
empid-03  Mike  35      Chicago  70000    Finance

- ZIP Function

In [65]:
# back working of ZIP function

marks = [90, 80, 60, 99, 87]
names = ["John", "Jane", "Mike", "Tom", "Jerry"]
dict1 = {}

for i, key in enumerate(names):
    # print(i, key)
    for j in range(len(marks)):
        # print(j, marks[j], marks[j][i])
        if i == j:
            dict1[key] = marks[j]
            
dict1

{'John': 90, 'Jane': 80, 'Mike': 60, 'Tom': 99, 'Jerry': 87}

In [3]:
marks = [90, 80, 60, 99, 87]
names = ["John", "Jane", "Mike", "Tom", "Jerry"]

In [4]:
results = list(zip(names, marks))
print(results)
# convert list of tuples to dictionary
final_results= dict(results)
final_results

[('John', 90), ('Jane', 80), ('Mike', 60), ('Tom', 99), ('Jerry', 87)]

{'John': 90, 'Jane': 80, 'Mike': 60, 'Tom': 99, 'Jerry': 87}

In [57]:
results = dict(zip(names, marks))
results

{'John': 90, 'Jane': 80, 'Mike': 60, 'Tom': 99, 'Jerry': 87}

- Dictionary Comprehension

In [68]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
for i in range(10):
    # i**2
    print(i**2, end=" ")

0 1 4 9 16 25 36 49 64 81

In [71]:
list3 = [i**2 for i in range(10)] # list comprehension
list3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [69]:
dict2 = {i : i**2 for i in range(10)}
dict2

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

- Fromkeys()

In [ ]:
# syntax = dict.fromkeys(iterable, value)

# It sets a perticular value to all the keys 
# A default value is None if not provided

In [5]:
dict.fromkeys(["a", "b", "c"], 0)

{'a': 0, 'b': 0, 'c': 0}

In [6]:
dict.fromkeys(["monday", "tuesday", "wednesday"], 2000)

{'monday': 2000, 'tuesday': 2000, 'wednesday': 2000}

In [7]:
dict.fromkeys(["monday", "tuesday", "wednesday"])

{'monday': None, 'tuesday': None, 'wednesday': None}

In [8]:
# question: 

dict.fromkeys(["iphone", "samsung", "nokia"], 20000)

{'iphone': 20000, 'samsung': 20000, 'nokia': 20000}

- Deep Copy
- Shallow Copy / Copy

In [19]:
# shallow copy : It works fine with simple dictionary but does not perform well with nested dictionary

In [ ]:
technologies = {"LLM": 20000, "AI": 50000, "ML": 40000, "DL": 50000}
technologies

{'LLM': 20000, 'AI': 30000, 'ML': 40000, 'DL': 50000}

In [10]:
copy_tech = technologies.copy()
copy_tech

{'LLM': 20000, 'AI': 30000, 'ML': 40000, 'DL': 50000}

In [11]:
copy_tech["LLM"] = 50000

In [12]:
copy_tech

{'LLM': 50000, 'AI': 30000, 'ML': 40000, 'DL': 50000}

In [13]:
technologies

{'LLM': 20000, 'AI': 30000, 'ML': 40000, 'DL': 50000}

In [14]:
# nested dictinary

technologies2 = {"LLM": {"name": "LLM", "price": 20000, "rating": 4.5},
                  "AI": {"name": "AI", "price": 50000, "rating": 4.8},
                  "ML": {"name": "ML", "price": 40000, "rating": 4.2},
                  "DL": {"name": "DL", "price": 50000, "rating": 4.7}}
technologies2

{'LLM': {'name': 'LLM', 'price': 20000, 'rating': 4.5},
 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8},
 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2},
 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}

In [15]:
tech_copy = technologies2.copy()

In [16]:
tech_copy

{'LLM': {'name': 'LLM', 'price': 20000, 'rating': 4.5},
 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8},
 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2},
 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}

In [17]:
tech_copy["LLM"]["price"] = 55000
tech_copy

{'LLM': {'name': 'LLM', 'price': 55000, 'rating': 4.5},
 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8},
 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2},
 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}

In [18]:
technologies2

{'LLM': {'name': 'LLM', 'price': 55000, 'rating': 4.5},
 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8},
 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2},
 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}

- Deep copy

In [20]:
from copy import deepcopy

In [24]:
technologies = {"LLM": 20000, "AI": 50000, "ML": 40000, "DL": 50000}
print("technology---->", technologies)

copy_tech1 = deepcopy(technologies)
print("copy_tech1---->", copy_tech1)

copy_tech1["LLM"] = 50000
print("copy_tech1---->", copy_tech1)

technology----> {'LLM': 20000, 'AI': 50000, 'ML': 40000, 'DL': 50000}
copy_tech1----> {'LLM': 20000, 'AI': 50000, 'ML': 40000, 'DL': 50000}
copy_tech1----> {'LLM': 50000, 'AI': 50000, 'ML': 40000, 'DL': 50000}

In [26]:
# nested dictinary

technologies2 = {"LLM": {"name": "LLM", "price": 20000, "rating": 4.5},
                  "AI": {"name": "AI", "price": 50000, "rating": 4.8},
                  "ML": {"name": "ML", "price": 40000, "rating": 4.2},
                  "DL": {"name": "DL", "price": 50000, "rating": 4.7}}
print("technology2---->", technologies2)

technology2----> {'LLM': {'name': 'LLM', 'price': 20000, 'rating': 4.5}, 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8}, 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2}, 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}

In [27]:
tech_copy2 = deepcopy(technologies2)
print("tech_copy2---->", tech_copy2)

tech_copy2["LLM"]["price"] = 55000
print("tech_copy2---->", tech_copy2)

print("technology2---->", technologies2)

tech_copy2----> {'LLM': {'name': 'LLM', 'price': 20000, 'rating': 4.5}, 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8}, 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2}, 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}
tech_copy2----> {'LLM': {'name': 'LLM', 'price': 55000, 'rating': 4.5}, 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8}, 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2}, 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}
technology2----> {'LLM': {'name': 'LLM', 'price': 20000, 'rating': 4.5}, 'AI': {'name': 'AI', 'price': 50000, 'rating': 4.8}, 'ML': {'name': 'ML', 'price': 40000, 'rating': 4.2}, 'DL': {'name': 'DL', 'price': 50000, 'rating': 4.7}}

In [ ]:
# shallow copy                               # deep copy 

1 works well with simple dict                1. works well with simple dict

2. does not work well with nested dict       2. works well with nested dict
(if I make changes in copy item, 
 those changes reflects in parent dict)