Data processing methods

data imbalancing treatment
null values treatment
outliers treatment
skew correction
encoding
hold out validation (data split)
model building
hyperparamter tuning
matrix evaluation

Encoding:
    is used to convert the object datatype into numerical datatypes.it converts the unique values of the object columns into numerical values.

Encoding techniques:
    replacing unique values with numbers
    Label encoding
    One hot encoding
    Get dummies

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import seaborn as sns 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('autos_dataset.csv')
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [3]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,195,196,197,198,199,200,201,202,203,204
symboling,3,3,1,2,2,2,1,1,1,0,...,-1,-2,-1,-2,-1,-1,-1,-1,-1,-1
normalized-losses,?,?,?,164,164,?,158,?,158,?,...,74,103,74,103,74,95,95,95,95,95
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,audi,...,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo
fuel-type,gas,gas,gas,gas,gas,gas,gas,gas,gas,gas,...,gas,gas,gas,gas,gas,gas,gas,gas,diesel,gas
aspiration,std,std,std,std,std,std,std,std,turbo,turbo,...,std,std,std,turbo,turbo,std,turbo,std,turbo,turbo
num-of-doors,two,two,two,four,four,two,four,four,four,two,...,four,four,four,four,four,four,four,four,four,four
body-style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,hatchback,...,wagon,sedan,wagon,sedan,wagon,sedan,sedan,sedan,sedan,sedan
drive-wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,4wd,...,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd
engine-location,front,front,front,front,front,front,front,front,front,front,...,front,front,front,front,front,front,front,front,front,front
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,99.5,...,104.3,104.3,104.3,104.3,104.3,109.1,109.1,109.1,109.1,109.1
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,178.2,...,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,67.9,...,67.2,67.2,67.2,67.2,67.2,68.9,68.8,68.9,68.9,68.9
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,52.0,...,57.5,56.2,57.5,56.2,57.5,55.5,55.5,55.5,55.5,55.5
curb-weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,3053,...,3034,2935,3042,3045,3157,2952,3049,3012,3217,3062
engine-type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,ohc,...,ohc,ohc,ohc,ohc,ohc,ohc,ohc,ohcv,ohc,ohc
num-of-cylinders,four,four,six,four,five,five,five,five,five,five,...,four,four,four,four,four,four,four,six,six,four
engine-size,130,130,152,109,136,136,136,136,131,131,...,141,141,141,130,130,141,141,173,145,141
fuel-system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,...,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,idi,mpfi
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,3.13,...,3.78,3.78,3.78,3.62,3.62,3.78,3.78,3.58,3.01,3.78
stroke,2.68,2.68,3.47,3.4,3.4,3.4,3.4,3.4,3.4,3.4,...,3.15,3.15,3.15,3.15,3.15,3.15,3.15,2.87,3.4,3.15
compression-ratio,9.0,9.0,9.0,10.0,8.0,8.5,8.5,8.5,8.3,7.0,...,9.5,9.5,9.5,7.5,7.5,9.5,8.7,8.8,23.0,9.5
horsepower,111,111,154,102,115,110,110,110,140,160,...,114,114,114,162,162,114,160,134,106,114
peak-rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,5500,...,5400,5400,5400,5100,5100,5400,5300,5500,4800,5400
city-mpg,21,21,19,24,18,19,19,19,17,16,...,23,24,24,17,17,23,19,18,26,19
highway-mpg,27,27,26,30,22,25,25,25,20,22,...,28,28,28,22,22,28,25,23,27,25
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,?,...,13415,15985,16515,18420,18950,16845,19045,21485,22470,22625

In [4]:
df.shape

(205, 26)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [6]:
df.replace({'?':np.nan},inplace=True)

In [7]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [8]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [9]:
df.symboling.nunique()

6

In [10]:
df.symboling.unique()

array([ 3,  1,  2,  0, -1, -2], dtype=int64)

In [11]:
df['normalized-losses'].isnull().sum()

41

In [12]:
df['normalized-losses'].unique()

array([nan, '164', '158', '192', '188', '121', '98', '81', '118', '148',
       '110', '145', '137', '101', '78', '106', '85', '107', '104', '113',
       '150', '129', '115', '93', '142', '161', '153', '125', '128',
       '122', '103', '168', '108', '194', '231', '119', '154', '74',
       '186', '83', '102', '89', '87', '77', '91', '134', '65', '197',
       '90', '94', '256', '95'], dtype=object)

In [13]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [14]:
df.drop(['make','fuel-type','aspiration','body-style', 'drive-wheels', 'engine-location','engine-type','fuel-system'],axis=1,inplace=True)

In [63]:
df

,symboling,normalized-losses,num-of-doors,wheel-base,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,115.0,two,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,115.0,two,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,115.0,two,94.5,171.2,65.5,52.4,2823,six,152,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,four,99.8,176.6,66.2,54.3,2337,four,109,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,four,99.4,176.6,66.4,54.3,2824,five,136,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,four,109.1,188.8,68.9,55.5,2952,four,141,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,four,109.1,188.8,68.8,55.5,3049,four,141,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,four,109.1,188.8,68.9,55.5,3012,six,173,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,four,109.1,188.8,68.9,55.5,3217,six,145,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,four,109.1,188.8,68.9,55.5,3062,four,141,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   num-of-doors       203 non-null    object
 3   wheel-base         205 non-null    float64
 4   length             205 non-null    float64
 5   width              205 non-null    float64
 6   height             205 non-null    float64
 7   curb-weight        205 non-null    int64
 8   num-of-cylinders   205 non-null    object
 9   engine-size        205 non-null    int64
 10  bore               201 non-null    object
 11  stroke             201 non-null    object
 12  compression-ratio  205 non-null    float64
 13  horsepower         203 non-null    object
 14  peak-rpm           203 non-null    object
 15  city-mpg           205 non-null    int64
 16  highway-mpg        205 non-null    int64
 17  price              201 non-null    object
dtypes: float64(5), int64(5), object(8)
memory usage: 29.0+ KB

In [17]:
df.fillna(df.median(),inplace=True)

In [18]:
df

,symboling,normalized-losses,num-of-doors,wheel-base,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,115.0,two,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111,5000,21,27,13495
1,3,115.0,two,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111,5000,21,27,16500
2,1,115.0,two,94.5,171.2,65.5,52.4,2823,six,152,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,four,99.8,176.6,66.2,54.3,2337,four,109,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,four,99.4,176.6,66.4,54.3,2824,five,136,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,four,109.1,188.8,68.9,55.5,2952,four,141,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,four,109.1,188.8,68.8,55.5,3049,four,141,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,four,109.1,188.8,68.9,55.5,3012,six,173,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,four,109.1,188.8,68.9,55.5,3217,six,145,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,four,109.1,188.8,68.9,55.5,3062,four,141,3.78,3.15,9.5,114,5400,19,25,22625

In [19]:
df.dtypes

symboling              int64
normalized-losses     object
num-of-doors          object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
num-of-cylinders      object
engine-size            int64
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [20]:
df['normalized-losses'].unique()

array([115.0, '164', '158', '192', '188', '121', '98', '81', '118', '148',
       '110', '145', '137', '101', '78', '106', '85', '107', '104', '113',
       '150', '129', '115', '93', '142', '161', '153', '125', '128',
       '122', '103', '168', '108', '194', '231', '119', '154', '74',
       '186', '83', '102', '89', '87', '77', '91', '134', '65', '197',
       '90', '94', '256', '95'], dtype=object)

In [21]:
df.bore.unique()

array(['3.47', '2.68', '3.19', '3.13', '3.5', '3.31', '3.62', '2.91',
       '3.03', '2.97', '3.34', '3.6', '2.92', '3.15', '3.43', '3.63',
       '3.54', '3.08', 3.31, '3.39', '3.76', '3.58', '3.46', '3.8',
       '3.78', '3.17', '3.35', '3.59', '2.99', '3.33', '3.7', '3.61',
       '3.94', '3.74', '2.54', '3.05', '3.27', '3.24', '3.01'],
      dtype=object)

In [22]:
df.stroke.unique()

array(['2.68', '3.47', '3.4', '2.8', '3.19', '3.39', '3.03', '3.11',
       '3.23', '3.46', '3.9', '3.41', '3.07', '3.58', '4.17', '2.76',
       '3.15', 3.29, '3.16', '3.64', '3.1', '3.35', '3.12', '3.86',
       '3.29', '3.27', '3.52', '2.19', '3.21', '2.9', '2.07', '2.36',
       '2.64', '3.08', '3.5', '3.54', '2.87'], dtype=object)

In [23]:
df.horsepower.unique()

array(['111', '154', '102', '115', '110', '140', '160', '101', '121',
       '182', '48', '70', '68', '88', '145', '58', '76', '60', '86',
       '100', '78', '90', '176', '262', '135', '84', '64', '120', '72',
       '123', '155', '184', '175', '116', '69', '55', '97', '152', '200',
       '95', '142', '143', '207', '288', 95.0, '73', '82', '94', '62',
       '56', '112', '92', '161', '156', '52', '85', '114', '162', '134',
       '106'], dtype=object)

In [24]:
df['peak-rpm'].unique()

array(['5000', '5500', '5800', '4250', '5400', '5100', '4800', '6000',
       '4750', '4650', '4200', '4350', '4500', '5200', '4150', '5600',
       '5900', '5750', 5200.0, '5250', '4900', '4400', '6600', '5300'],
      dtype=object)

In [25]:
df.price.unique()

array(['13495', '16500', '13950', '17450', '15250', '17710', '18920',
       '23875', 10295.0, '16430', '16925', '20970', '21105', '24565',
       '30760', '41315', '36880', '5151', '6295', '6575', '5572', '6377',
       '7957', '6229', '6692', '7609', '8558', '8921', '12964', '6479',
       '6855', '5399', '6529', '7129', '7295', '7895', '9095', '8845',
       '10295', '12945', '10345', '6785', '11048', '32250', '35550',
       '36000', '5195', '6095', '6795', '6695', '7395', '10945', '11845',
       '13645', '15645', '8495', '10595', '10245', '10795', '11245',
       '18280', '18344', '25552', '28248', '28176', '31600', '34184',
       '35056', '40960', '45400', '16503', '5389', '6189', '6669', '7689',
       '9959', '8499', '12629', '14869', '14489', '6989', '8189', '9279',
       '5499', '7099', '6649', '6849', '7349', '7299', '7799', '7499',
       '7999', '8249', '8949', '9549', '13499', '14399', '17199', '19699',
       '18399', '11900', '13200', '12440', '13860', '15580', '16900',
       '16695', '17075', '16630', '17950', '18150', '12764', '22018',
       '32528', '34028', '37028', '9295', '9895', '11850', '12170',
       '15040', '15510', '18620', '5118', '7053', '7603', '7126', '7775',
       '9960', '9233', '11259', '7463', '10198', '8013', '11694', '5348',
       '6338', '6488', '6918', '7898', '8778', '6938', '7198', '7788',
       '7738', '8358', '9258', '8058', '8238', '9298', '9538', '8449',
       '9639', '9989', '11199', '11549', '17669', '8948', '10698', '9988',
       '10898', '11248', '16558', '15998', '15690', '15750', '7975',
       '7995', '8195', '9495', '9995', '11595', '9980', '13295', '13845',
       '12290', '12940', '13415', '15985', '16515', '18420', '18950',
       '16845', '19045', '21485', '22470', '22625'], dtype=object)

In [26]:
df['bore']= df['bore'].astype(float)
df['normalized-losses']= df['normalized-losses'].astype(float)
df['stroke']= df['stroke'].astype(float)
df['peak-rpm']= df['peak-rpm'].astype(float)
df['price']= df['price'].astype(float)
df['horsepower']= df['horsepower'].astype(float)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    float64
 2   num-of-doors       203 non-null    object
 3   wheel-base         205 non-null    float64
 4   length             205 non-null    float64
 5   width              205 non-null    float64
 6   height             205 non-null    float64
 7   curb-weight        205 non-null    int64
 8   num-of-cylinders   205 non-null    object
 9   engine-size        205 non-null    int64
 10  bore               205 non-null    float64
 11  stroke             205 non-null    float64
 12  compression-ratio  205 non-null    float64
 13  horsepower         205 non-null    float64
 14  peak-rpm           205 non-null    float64
 15  city-mpg           205 non-null    int64
 16  highway-mpg        205 non-null    int64
 17  price              205 non-null    float64
dtypes: float64(11), int64(5), object(2)
memory usage: 29.0+ KB

In [28]:
df['num-of-doors'].unique()

array(['two', 'four', nan], dtype=object)

In [29]:
df['num-of-doors'].isnull().sum()

2

In [30]:
df['num-of-doors'].value_counts()

four    114
two      89
Name: num-of-doors, dtype: int64

In [31]:
df['num-of-doors'].fillna('four',inplace=True)

In [32]:
df['num-of-doors'].unique()

array(['two', 'four'], dtype=object)

In [33]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [34]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()

# simplest Encoding:replacing the unique values with numbers

In [35]:
df1['num-of-doors'].replace({'two':2,'four':4},inplace=True)

In [36]:
df1.dtypes

symboling              int64
normalized-losses    float64
num-of-doors           int64
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
num-of-cylinders      object
engine-size            int64
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

# Label Encoder

In [37]:
df1['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [38]:
sorted(df1['num-of-cylinders'].unique())

['eight', 'five', 'four', 'six', 'three', 'twelve', 'two']

In [39]:
df1['num-of-cylinders'].head(60)

0       four
1       four
2        six
3       four
4       five
5       five
6       five
7       five
8       five
9       five
10      four
11      four
12       six
13       six
14       six
15       six
16       six
17       six
18     three
19      four
20      four
21      four
22      four
23      four
24      four
25      four
26      four
27      four
28      four
29      four
30      four
31      four
32      four
33      four
34      four
35      four
36      four
37      four
38      four
39      four
40      four
41      four
42      four
43      four
44      four
45      four
46      four
47       six
48       six
49    twelve
50      four
51      four
52      four
53      four
54      four
55       two
56       two
57       two
58       two
59      four
Name: num-of-cylinders, dtype: object

In [40]:
# creating an instance

label_enco = LabelEncoder()
label_enco.fit_transform(df1['num-of-cylinders'])

array([2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 3, 5, 2, 2, 2, 2, 2, 6, 6, 6, 6, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 2])

In [41]:
df1['num-of-cylinders'] = label_enco.fit_transform(df1['num-of-cylinders'])

In [42]:
df1.dtypes

symboling              int64
normalized-losses    float64
num-of-doors           int64
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
num-of-cylinders       int32
engine-size            int64
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

# One hot encoder

In [43]:
df2['num-of-doors']

0       two
1       two
2       two
3      four
4      four
       ...
200    four
201    four
202    four
203    four
204    four
Name: num-of-doors, Length: 205, dtype: object

In [44]:
one_hot_enco = OneHotEncoder()
array = one_hot_enco.fit_transform(df2[['num-of-doors']]).toarray()
num_of_cyl = pd.DataFrame(array,columns=sorted(df2['num-of-doors'].unique()))
num_of_cyl

     four  two
0     0.0  1.0
1     0.0  1.0
2     0.0  1.0
3     1.0  0.0
4     1.0  0.0
..    ...  ...
200   1.0  0.0
201   1.0  0.0
202   1.0  0.0
203   1.0  0.0
204   1.0  0.0

[205 rows x 2 columns]

In [45]:
new_df = pd.concat([df2,num_of_cyl],axis=1).drop('num-of-doors',axis=1)
new_df

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,four,two
0,3,115.0,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,0.0,1.0
1,3,115.0,88.6,168.8,64.1,48.8,2548,four,130,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,0.0,1.0
2,1,115.0,94.5,171.2,65.5,52.4,2823,six,152,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,0.0,1.0
3,2,164.0,99.8,176.6,66.2,54.3,2337,four,109,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,1.0,0.0
4,2,164.0,99.4,176.6,66.4,54.3,2824,five,136,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,109.1,188.8,68.9,55.5,2952,four,141,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0,1.0,0.0
201,-1,95.0,109.1,188.8,68.8,55.5,3049,four,141,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0,1.0,0.0
202,-1,95.0,109.1,188.8,68.9,55.5,3012,six,173,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0,1.0,0.0
203,-1,95.0,109.1,188.8,68.9,55.5,3217,six,145,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0,1.0,0.0
204,-1,95.0,109.1,188.8,68.9,55.5,3062,four,141,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,1.0,0.0

# getdummies

In [64]:
df2.get('num-of-cylinders').unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [47]:
df_get_dum = pd.get_dummies(df2,columns=['num-of-cylinders','num-of-doors'],drop_first=True)
df_get_dum

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,...,city-mpg,highway-mpg,price,num-of-cylinders_five,num-of-cylinders_four,num-of-cylinders_six,num-of-cylinders_three,num-of-cylinders_twelve,num-of-cylinders_two,num-of-doors_two
0,3,115.0,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,21,27,13495.0,0,1,0,0,0,0,1
1,3,115.0,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,21,27,16500.0,0,1,0,0,0,0,1
2,1,115.0,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,...,19,26,16500.0,0,0,1,0,0,0,1
3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,...,24,30,13950.0,0,1,0,0,0,0,0
4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,...,18,22,17450.0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,...,23,28,16845.0,0,1,0,0,0,0,0
201,-1,95.0,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,...,19,25,19045.0,0,1,0,0,0,0,0
202,-1,95.0,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,...,18,23,21485.0,0,0,1,0,0,0,0
203,-1,95.0,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,...,26,27,22470.0,0,0,1,0,0,0,0
204,-1,95.0,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,...,19,25,22625.0,0,1,0,0,0,0,0

In [48]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    float64
 2   num-of-doors       205 non-null    int64
 3   wheel-base         205 non-null    float64
 4   length             205 non-null    float64
 5   width              205 non-null    float64
 6   height             205 non-null    float64
 7   curb-weight        205 non-null    int64
 8   num-of-cylinders   205 non-null    int32
 9   engine-size        205 non-null    int64
 10  bore               205 non-null    float64
 11  stroke             205 non-null    float64
 12  compression-ratio  205 non-null    float64
 13  horsepower         205 non-null    float64
 14  peak-rpm           205 non-null    float64
 15  city-mpg           205 non-null    int64
 16  highway-mpg        205 non-null    int64
 17  price              205 non-null    float64
dtypes: float64(11), int32(1), int64(6)
memory usage: 28.2 KB

In [49]:
x = df1.drop('price',axis='columns')
y = df1.price

In [50]:
df1.dtypes

symboling              int64
normalized-losses    float64
num-of-doors           int64
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
num-of-cylinders       int32
engine-size            int64
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

In [51]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15,random_state=3)

In [52]:
linear_model = LinearRegression()
linear_model

LinearRegression()

In [53]:
linear_model.fit(x_train,y_train)

LinearRegression()

# residual

residual = y_actual - y_pred
residuals = sum(y_actual - y_pred)

In [54]:
y_pred = linear_model.predict(x_test)
print('mse is - ',mean_squared_error(y_test,y_pred))
print('r2 score is - ',r2_score(y_test,y_pred))

mse is -  17882796.284611836
r2 score is -  0.7193092470150513

y = mx+c
y = m1x1+m2x2+m3x3+......+mnxn+c

In [55]:
linear_model.coef_    # to check the values of coefficients or slopes

array([ 5.69518484e+02, -5.83475627e+00,  3.47250063e+02,  6.43300870e+01,
       -6.22660224e+01,  1.88340422e+02,  3.81229008e+02,  1.64485550e+00,
        1.04934496e+03,  1.60182325e+02, -5.55246399e+02, -2.82095800e+03,
        2.60918564e+02, -1.73705913e+01,  3.70828789e+00, -4.71549154e+01,
       -1.23179496e+02])

In [56]:
df.shape

(205, 18)

In [57]:
df.shape[1]-1

17

In [58]:
len(linear_model.coef_)

17

In [59]:
linear_model.intercept_    # to check the value of intercept C

-46627.711035448985

# --------------------------------------------------

In [60]:
x = df_get_dum.drop('price',axis='columns')
y = df_get_dum.price

In [61]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15,random_state=52)
linear_model = LinearRegression()
linear_model.fit(x_train,y_train)
y_pred = linear_model.predict(x_test)
print('mse is - ',mean_squared_error(y_test,y_pred))
print('r2 score is - ',r2_score(y_test,y_pred))

mse is -  8922839.809463406
r2 score is -  0.7485900079172891