## PANDAS --> Python Data Analysis
( Built in library )

- Two data structures in Pandas
1. 1D --> Series
2. 2D --> DataFrame

- DataFrame :
 *  2 dimentional data table with mutable rows and columns

  ** Mutable (Add, Update, Delete, Rename, Replace)

In [1]:
# # Application:
# 1. Used for working on datasets
# 2. Analysis, Visualization, Cleaning, Processing, Mining, Wrangling, Manupulation of the data
# 3. Join Multiple tables --> SQL (all sqp ops can be done in Pandas)
# 4. Create excel, csv, json etc
# 5. Files mathematical operations

In [2]:
import pandas as pd
import numpy as np

In [ ]:
from typing import Dict
# There are multiple ways how we can create a dataframe
1. Excel
2. CSV
3. JSON
4. Mongodb database
5. SQL database
6. Copy from Clipboard
7. List
8. Array
9. Dict

### Creating A DataFrame

In [4]:
data = {"column A": [2, 3, 4, 5], "column B": [9, 8, 7, 6]}
type(data)

dict

In [5]:
dataframe = pd.DataFrame(data)
dataframe

   column A  column B
0         2         9
1         3         8
2         4         7
3         5         6

In [20]:
# Columns in DataFrame --> Features = Variables = Fields = Dimensions
# Rows in DataFrame --> Records = Values = Observations = Index

In [6]:
data2 = np.array([33, 44, 55, 66])
data2

array([33, 44, 55, 66])

In [8]:
df = pd.DataFrame(data2, columns=['values'])
df

   values
0      33
1      44
2      55
3      66

In [10]:
data3 = [44, 55, 66, 77]

df = pd.DataFrame(data3, columns=['Vals'])
df

   Vals
0    44
1    55
2    66
3    77

## Export a dataframe

In [11]:
dataframe = pd.DataFrame(data)
dataframe

   column A  column B
0         2         9
1         3         8
2         4         7
3         5         6

In [13]:
dataframe.to_excel('dataframe.xlsx')

In [14]:
dataframe.to_csv('dataframe.csv')

In [15]:
dataframe.to_json('dataframe.json')

In [18]:
dataframe.to_clipboard("file.png")

<ipython-input-18-985049b1769a>:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_clipboard will be keyword-only.
  dataframe.to_clipboard("file.png")

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

## Create an empty dataframe

In [19]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

### How to add a column

In [21]:
dataframe = pd.DataFrame(data)
dataframe

   column A  column B
0         2         9
1         3         8
2         4         7
3         5         6

In [22]:
dataframe['column C'] = "AI"
dataframe

   column A  column B column C
0         2         9       AI
1         3         8       AI
2         4         7       AI
3         5         6       AI

In [25]:
dataframe['column C'] = "GenAI" # Overwrite
dataframe

   column A  column B column C
0         2         9    GenAI
1         3         8    GenAI
2         4         7    GenAI
3         5         6    GenAI

In [26]:
dataframe['column C'] = ['G', 'E', 'N', "AI"]
dataframe

   column A  column B column C
0         2         9        G
1         3         8        E
2         4         7        N
3         5         6       AI

In [27]:
dataframe['column C'] = list('gene')
dataframe

   column A  column B column C
0         2         9        g
1         3         8        e
2         4         7        n
3         5         6        e

In [28]:
dataframe['column D'] = np.array([100, 200, 300, 400])
dataframe

   column A  column B column C  column D
0         2         9        g       100
1         3         8        e       200
2         4         7        n       300
3         5         6        e       400

In [30]:
# Add a column E

dataframe['column D'] = [1, 2, 3, 4]
dataframe

   column A  column B column C  column D  column d
0         2         9        g       100         1
1         3         8        e       200         2
2         4         7        n       300         3
3         5         6        e       400         4

In [32]:
dataframe['column E']=['genz','gena','genb', 'genG']
dataframe

   column A  column B column C  column D  column d column E
0         2         9        g       100         1     genz
1         3         8        e       200         2     gena
2         4         7        n       300         3     genb
3         5         6        e       400         4     genG

## Setting a column as index

In [33]:
dataframe['index'] = np.array([1, 2, 3, 4])
dataframe

   column A  column B column C  column D  column d column E  index
0         2         9        g       100         1     genz      1
1         3         8        e       200         2     gena      2
2         4         7        n       300         3     genb      3
3         5         6        e       400         4     genG      4

In [34]:
df = dataframe.set_index('index')
df

       column A  column B column C  column D  column d column E
index
1             2         9        g       100         1     genz
2             3         8        e       200         2     gena
3             4         7        n       300         3     genb
4             5         6        e       400         4     genG

## Loading a data in Pandas

In [36]:
df = pd.read_csv('/content/Students Social Media Addiction.csv')
df

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

In [37]:
df.shape

(705, 13)

In [38]:
df.index

RangeIndex(start=0, stop=705, step=1)

In [39]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Relationship_Status',
       'Conflicts_Over_Social_Media', 'Addicted_Score'],
      dtype='object')

In [41]:
df['my column'] = np.random.randint(1, 705, 705)
df

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score,my column
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8,684
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3,357
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9,319
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4,39
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5,78
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9,601
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7,148
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4,287
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8,664

In [42]:
df.axes

[RangeIndex(start=0, stop=705, step=1),
 Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
        'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
        'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
        'Mental_Health_Score', 'Relationship_Status',
        'Conflicts_Over_Social_Media', 'Addicted_Score', 'my column'],
       dtype='object')]