## Filters

### isin function

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/content/employees.csv")
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB

In [9]:
new = data['Gender'].isin(['Male'])
# display(new)

data.loc[new]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [12]:
data.groupby('Gender').get_group('Female')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
988,Alice,Female,10/5/2004,9:34 AM,47638,11.209,False,Human Resources
990,Robin,Female,7/24/1987,1:35 PM,100765,10.982,True,Client Services
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering

In [14]:
data.loc[~(data['Gender']=='Male')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
989,Justin,NaN,2/10/1991,4:58 PM,38344,3.794,False,Legal
990,Robin,Female,7/24/1987,1:35 PM,100765,10.982,True,Client Services
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution

In [13]:
data.loc[data['Gender']=='Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [11]:
data.loc[data['Gender'].isin(['Female'])]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
988,Alice,Female,10/5/2004,9:34 AM,47638,11.209,False,Human Resources
990,Robin,Female,7/24/1987,1:35 PM,100765,10.982,True,Client Services
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering

In [16]:
data.loc[np.where(data['Gender']=='Male')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [21]:
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [50]:
data.loc[(data['Team']=='Finance')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,7/27/1998,11:12 AM,137144,10.081,False,Finance
954,Joe,Male,1/19/1980,4:06 PM,119667,1.148,True,Finance
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance

In [51]:
data.loc[(data['Team'].isin(['Finance']))]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,7/27/1998,11:12 AM,137144,10.081,False,Finance
954,Joe,Male,1/19/1980,4:06 PM,119667,1.148,True,Finance
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance

In [49]:
data.groupby('Team').get_group('Finance')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,7/27/1998,11:12 AM,137144,10.081,False,Finance
954,Joe,Male,1/19/1980,4:06 PM,119667,1.148,True,Finance
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance

In [52]:
data.loc[np.where(data['Team']=='Finance')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,7/27/1998,11:12 AM,137144,10.081,False,Finance
954,Joe,Male,1/19/1980,4:06 PM,119667,1.148,True,Finance
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance

In [ ]:
# give me all the Senior Management people --> True
# groupby + get group
# LOC :
#   isin
#   np.where

In [43]:
data.groupby('Senior Management').get_group(True)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [45]:
data.loc[(data['Senior Management'].isin([True]))]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [48]:
data.loc[np.where(data['Senior Management']==True)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,8/25/2002,5:12 AM,134505,11.051,True,Marketing
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [39]:
np.where(data["Salary"]==97308)

(array([0]),)

In [40]:
data.loc[np.where(data["Salary"]==97308)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing

In [41]:
data.groupby('Salary').get_group(97308)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB