# Sorting --> Filters

## Sorting

In [ ]:
# sort_index() --> Axes sort (Columns + Rows)
# sort_values() --> Value sort (Columns + Rows)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Emp_Records.csv")
df

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City
0,677509,Lois,36.36,NaN,13.68,168251,NaN
1,940761,Brenda,47.02,NaN,NaN,51063,Stonewall
2,428945,Joe,54.15,68.0,0.98,50155,Michigantown
3,408351,Diane,39.67,NaN,18.30,180294,Hydetown
4,193819,Benjamin,40.31,58.0,4.01,117642,Fremont
...,...,...,...,...,...,...,...
95,639892,Jose,22.82,89.0,1.05,129774,Biloxi
96,704709,Harold,32.61,77.0,5.93,156194,Carol Stream
97,461593,Nicole,52.66,60.0,28.53,95673,Detroit
98,392491,Theresa,29.60,57.0,6.99,51015,Mc Grath
99,495141,Tammy,38.38,55.0,2.26,93650,Alma

In [3]:
# sorting indexes

In [4]:
df.sort_index(axis=0) #rows sorting

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City
0,677509,Lois,36.36,NaN,13.68,168251,NaN
1,940761,Brenda,47.02,NaN,NaN,51063,Stonewall
2,428945,Joe,54.15,68.0,0.98,50155,Michigantown
3,408351,Diane,39.67,NaN,18.30,180294,Hydetown
4,193819,Benjamin,40.31,58.0,4.01,117642,Fremont
...,...,...,...,...,...,...,...
95,639892,Jose,22.82,89.0,1.05,129774,Biloxi
96,704709,Harold,32.61,77.0,5.93,156194,Carol Stream
97,461593,Nicole,52.66,60.0,28.53,95673,Detroit
98,392491,Theresa,29.60,57.0,6.99,51015,Mc Grath
99,495141,Tammy,38.38,55.0,2.26,93650,Alma

In [5]:
df.sort_index(axis=1) #column sorting

,Age in Company,Age in Yrs,City,Emp ID,First Name,Salary,Weight in Kgs
0,13.68,36.36,NaN,677509,Lois,168251,NaN
1,NaN,47.02,Stonewall,940761,Brenda,51063,NaN
2,0.98,54.15,Michigantown,428945,Joe,50155,68.0
3,18.30,39.67,Hydetown,408351,Diane,180294,NaN
4,4.01,40.31,Fremont,193819,Benjamin,117642,58.0
...,...,...,...,...,...,...,...
95,1.05,22.82,Biloxi,639892,Jose,129774,89.0
96,5.93,32.61,Carol Stream,704709,Harold,156194,77.0
97,28.53,52.66,Detroit,461593,Nicole,95673,60.0
98,6.99,29.60,Mc Grath,392491,Theresa,51015,57.0
99,2.26,38.38,Alma,495141,Tammy,93650,55.0

In [6]:
df1 = df.set_index('City') # we changed the rows to cities
df1

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary
City,,,,,,
NaN,677509,Lois,36.36,NaN,13.68,168251
Stonewall,940761,Brenda,47.02,NaN,NaN,51063
Michigantown,428945,Joe,54.15,68.0,0.98,50155
Hydetown,408351,Diane,39.67,NaN,18.30,180294
Fremont,193819,Benjamin,40.31,58.0,4.01,117642
...,...,...,...,...,...,...
Biloxi,639892,Jose,22.82,89.0,1.05,129774
Carol Stream,704709,Harold,32.61,77.0,5.93,156194
Detroit,461593,Nicole,52.66,60.0,28.53,95673
Mc Grath,392491,Theresa,29.60,57.0,6.99,51015
Alma,495141,Tammy,38.38,55.0,2.26,93650

In [7]:
df1.sort_index(axis=0)

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary
City,,,,,,
Albion,765850,Linda,25.96,40.0,0.20,113256
Alcoa,316110,Jeremy,52.51,52.0,11.33,178847
Alma,495141,Tammy,38.38,55.0,2.26,93650
Arlee,904898,Ann,24.61,44.0,0.45,182521
Atlanta,539712,Nancy,22.14,50.0,0.87,98189
...,...,...,...,...,...,...
Wichita,476433,Lillian,42.79,55.0,17.65,149878
Willow Beach,917395,Christopher,57.37,62.0,19.73,190765
Woodbury,388642,Ruby,37.27,59.0,3.91,160623
Wright,726264,Carl,43.63,90.0,10.14,162159
NaN,677509,Lois,36.36,NaN,13.68,168251

In [9]:
df2 = df.set_index('Salary')
df2.sort_index(axis=0)

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,City
Salary,,,,,,
42005,560455,Carolyn,59.42,53.0,16.08,Saint Cloud
43010,162402,Diana,29.73,60.0,3.44,Eureka Springs
43867,951225,Margaret,25.10,56.0,0.92,Haswell
46945,687017,Frances,56.53,42.0,6.94,Trego
48736,325319,Carolyn,41.19,60.0,2.73,Wheaton
...,...,...,...,...,...,...
186200,478003,Cynthia,54.16,60.0,13.41,Kansas City
186280,265813,Jack,32.58,50.0,10.01,Kalvesta
190139,253573,Sharon,26.25,43.0,3.39,Bartley
190765,917395,Christopher,57.37,62.0,19.73,Willow Beach
197537,214352,Theresa,24.66,59.0,2.52,Toeterville

## Transpose of a Matrix

In [11]:
df1 = df.T
df1

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
Emp ID,677509,940761,428945,408351,193819,499687,539712,380086,477616,162402,...,185032,867084,969964,158666,489424,639892,704709,461593,392491,495141
First Name,Lois,Brenda,Joe,Diane,Benjamin,Patrick,Nancy,Carol,Frances,Diana,...,Eugene,Deborah,Janice,Rebecca,Phillip,Jose,Harold,Nicole,Theresa,Tammy
Age in Yrs,36.36,47.02,54.15,39.67,40.31,34.86,22.14,59.12,58.18,29.73,...,37.84,39.77,37.57,56.0,39.43,22.82,32.61,52.66,29.6,38.38
Weight in Kgs,NaN,NaN,68.0,NaN,58.0,58.0,50.0,40.0,42.0,60.0,...,59.0,54.0,56.0,55.0,82.0,89.0,77.0,60.0,57.0,55.0
Age in Company,13.68,NaN,0.98,18.3,4.01,12.02,0.87,34.52,23.27,3.44,...,2.64,15.41,0.93,34.32,1.56,1.05,5.93,28.53,6.99,2.26
Salary,168251,51063,50155,180294,117642,72305,98189,60918,121587,43010,...,122950,52767,147641,160043,181774,129774,156194,95673,51015,93650
City,NaN,Stonewall,Michigantown,Hydetown,Fremont,Macksburg,Atlanta,Blanchester,Delmita,Eureka Springs,...,Racine,Atqasuk,Whiteman Air Force Base,Independence,Mapleton,Biloxi,Carol Stream,Detroit,Mc Grath,Alma

### Sort Values

In [17]:
df.sort_values('Age in Yrs', ascending=False).head() #top 5 oldest people in the company

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City
14,441771,Cheryl,59.47,47.0,26.69,92220,Quecreek
24,560455,Carolyn,59.42,53.0,16.08,42005,Saint Cloud
57,515103,Anne,59.27,48.0,14.01,114426,Cookeville
7,380086,Carol,59.12,40.0,34.52,60918,Blanchester
74,528673,Paul,58.43,60.0,22.10,145235,Blue River

In [13]:
df.sort_values('Age in Yrs', ascending=True)

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City
13,301576,Wayne,21.10,87.0,0.02,92758,Maida
49,879753,Pamela,21.30,47.0,0.13,149262,Banner
59,750173,Antonio,21.93,82.0,0.24,181646,Mc Calla
6,539712,Nancy,22.14,50.0,0.87,98189,Atlanta
11,153989,Jack,22.21,61.0,0.56,82965,Las Vegas
...,...,...,...,...,...,...,...
74,528673,Paul,58.43,60.0,22.10,145235,Blue River
7,380086,Carol,59.12,40.0,34.52,60918,Blanchester
57,515103,Anne,59.27,48.0,14.01,114426,Cookeville
24,560455,Carolyn,59.42,53.0,16.08,42005,Saint Cloud
14,441771,Cheryl,59.47,47.0,26.69,92220,Quecreek

### Who's ages is less but salary is more

In [21]:
df.sort_values(['Age in Yrs', 'Salary'], ascending=[True, False])

,Emp ID,First Name,Age in Yrs,Weight in Kgs,Age in Company,Salary,City
13,301576,Wayne,21.10,87.0,0.02,92758,Maida
49,879753,Pamela,21.30,47.0,0.13,149262,Banner
59,750173,Antonio,21.93,82.0,0.24,181646,Mc Calla
6,539712,Nancy,22.14,50.0,0.87,98189,Atlanta
11,153989,Jack,22.21,61.0,0.56,82965,Las Vegas
...,...,...,...,...,...,...,...
74,528673,Paul,58.43,60.0,22.10,145235,Blue River
7,380086,Carol,59.12,40.0,34.52,60918,Blanchester
57,515103,Anne,59.27,48.0,14.01,114426,Cookeville
24,560455,Carolyn,59.42,53.0,16.08,42005,Saint Cloud
14,441771,Cheryl,59.47,47.0,26.69,92220,Quecreek

## Filters

In [22]:
df = pd.read_csv("/content/movies_data.csv")
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [27]:
# Unique()

df.content_rating.unique()
df.genre.unique()

array(['Crime', 'Action', 'Drama', 'Western', 'Adventure', 'Biography',
       'Comedy', 'Animation', 'Mystery', 'Horror', 'Film-Noir', 'Sci-Fi',
       'History', 'Thriller', 'Family', 'Fantasy'], dtype=object)

In [28]:
len(df.genre.unique())

16

In [29]:
df.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [30]:
# Value_counts()

df.genre.value_counts()

genre
Drama        278
Comedy       156
Action       136
Crime        124
Biography     77
Adventure     75
Animation     62
Horror        29
Mystery       16
Western        9
Sci-Fi         5
Thriller       5
Film-Noir      3
Family         2
History        1
Fantasy        1
Name: count, dtype: int64

In [31]:
df.content_rating.value_counts()

content_rating
R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
PASSED         7
NC-17          7
X              4
GP             3
TV-MA          1
Name: count, dtype: int64

### Groupby & Get_group

In [32]:
df.groupby('genre')

In [33]:
df.groupby('genre').first()

,star_rating,title,content_rating,duration,actors_list
genre,,,,,
Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Adventure,8.9,The Lord of the Rings: The Return of the King,PG-13,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
Animation,8.6,Spirited Away,PG,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
Biography,8.9,Schindler's List,R,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
Comedy,8.6,Life Is Beautiful,PG-13,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
Drama,8.9,12 Angry Men,NOT RATED,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
Family,7.9,E.T. the Extra-Terrestrial,PG,115,"[u'Henry Thomas', u'Drew Barrymore', u'Peter C..."
Fantasy,7.7,The City of Lost Children,R,112,"[u'Ron Perlman', u'Daniel Emilfork', u'Judith ..."
Film-Noir,8.3,The Third Man,NOT RATED,93,"[u'Orson Welles', u'Joseph Cotten', u'Alida Va..."
History,8.0,Battleship Potemkin,UNRATED,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
Horror,8.6,Psycho,R,109,"[u'Anthony Perkins', u'Janet Leigh', u'Vera Mi..."
Mystery,8.6,Rear Window,APPROVED,112,"[u'James Stewart', u'Grace Kelly', u'Wendell C..."
Sci-Fi,8.2,Blade Runner,R,117,"[u'Harrison Ford', u'Rutger Hauer', u'Sean You..."
Thriller,8.0,Shadow of a Doubt,APPROVED,108,"[u'Teresa Wright', u'Joseph Cotten', u'Macdona..."
Western,8.9,"The Good, the Bad and the Ugly",NOT RATED,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."

In [34]:
df.groupby('genre').last()

,star_rating,title,content_rating,duration,actors_list
genre,,,,,
Action,7.4,Master and Commander: The Far Side of the World,PG-13,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
Adventure,7.4,Back to the Future Part III,PG,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
Animation,7.4,The Simpsons Movie,PG-13,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
Biography,7.4,Lincoln,PG-13,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
Comedy,7.4,Tootsie,PG,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
Crime,7.4,Wall Street,R,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."
Drama,7.4,The Cider House Rules,PG-13,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
Family,7.8,Willy Wonka & the Chocolate Factory,G,100,"[u'Gene Wilder', u'Jack Albertson', u'Peter Os..."
Fantasy,7.7,The City of Lost Children,R,112,"[u'Ron Perlman', u'Daniel Emilfork', u'Judith ..."
Film-Noir,7.7,Spellbound,UNRATED,111,"[u'Ingrid Bergman', u'Gregory Peck', u'Michael..."
History,8.0,Battleship Potemkin,UNRATED,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
Horror,7.4,Poltergeist,PG,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
Mystery,7.4,Limitless,PG-13,105,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor..."
Sci-Fi,7.7,The Butterfly Effect,R,113,"[u'Ashton Kutcher', u'Amy Smart', u'Melora Wal..."
Thriller,7.5,Frenzy,R,116,"[u'Jon Finch', u'Barry Foster', u'Alec McCowen']"
Western,7.6,High Plains Drifter,R,105,"[u'Clint Eastwood', u'Verna Bloom', u'Marianna..."

In [35]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [36]:
df.groupby('genre').get_group('Adventure')

,star_rating,title,content_rating,genre,duration,actors_list
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
14,8.8,The Lord of the Rings: The Two Towers,PG-13,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort..."
15,8.7,Interstellar,PG-13,Adventure,169,"[u'Matthew McConaughey', u'Anne Hathaway', u'J..."
54,8.5,Back to the Future,PG,Adventure,116,"[u'Michael J. Fox', u'Christopher Lloyd', u'Le..."
...,...,...,...,...,...,...
936,7.4,True Grit,NaN,Adventure,128,"[u'John Wayne', u'Kim Darby', u'Glen Campbell']"
937,7.4,Labyrinth,PG,Adventure,101,"[u'David Bowie', u'Jennifer Connelly', u'Toby ..."
943,7.4,The Bucket List,PG-13,Adventure,97,"[u'Jack Nicholson', u'Morgan Freeman', u'Sean ..."
953,7.4,The NeverEnding Story,PG,Adventure,102,"[u'Noah Hathaway', u'Barret Oliver', u'Tami St..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."

In [37]:
df.groupby('content_rating').get_group('PG-13')

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
13,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
...,...,...,...,...,...,...
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
965,7.4,Limitless,PG-13,Mystery,105,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor..."
966,7.4,The Simpsons Movie,PG-13,Animation,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [38]:
df.groupby('star_rating').get_group(9.0)

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."

In [41]:
df.groupby(['content_rating', 'genre']).get_group(('R', 'Crime'))

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
...,...,...,...,...,...,...
927,7.5,Brick,R,Crime,110,"[u'Joseph Gordon-Levitt', u'Lukas Haas', u'Emi..."
931,7.4,Mean Streets,R,Crime,112,"[u'Robert De Niro', u'Harvey Keitel', u'David ..."
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [43]:
df.groupby(['content_rating', 'genre'])['duration'].sum()

content_rating  genre
APPROVED        Action       430
                Adventure    475
                Animation    254
                Biography    111
                Comedy       975
                            ...
UNRATED         Mystery       86
X               Comedy        84
                Crime        136
                Drama        113
                Horror        92
Name: duration, Length: 95, dtype: int64

In [44]:
df.groupby(['content_rating', 'genre'])['duration'].sum().reset_index()

   content_rating      genre  duration
0        APPROVED     Action       430
1        APPROVED  Adventure       475
2        APPROVED  Animation       254
3        APPROVED  Biography       111
4        APPROVED     Comedy       975
..            ...        ...       ...
90        UNRATED    Mystery        86
91              X     Comedy        84
92              X      Crime       136
93              X      Drama       113
94              X     Horror        92

[95 rows x 3 columns]

## LOC

In [46]:
df.loc[df['genre']=='Crime']

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
...,...,...,...,...,...,...
927,7.5,Brick,R,Crime,110,"[u'Joseph Gordon-Levitt', u'Lukas Haas', u'Emi..."
931,7.4,Mean Streets,R,Crime,112,"[u'Robert De Niro', u'Harvey Keitel', u'David ..."
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [47]:
df.loc[(df['genre']=='Crime')&(df['content_rating']=='PG')] # It will consider both the conditions mentioned

,star_rating,title,content_rating,genre,duration,actors_list
154,8.2,Cool Hand Luke,PG,Crime,126,"[u'Paul Newman', u'George Kennedy', u'Strother..."
171,8.2,Dial M for Murder,PG,Crime,105,"[u'Ray Milland', u'Grace Kelly', u'Robert Cumm..."
200,8.1,Le Samourai,PG,Crime,101,"[u'Alain Delon', u'Nathalie Delon', u'Fran\xe7..."
297,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran..."
425,7.9,Badlands,PG,Crime,94,"[u'Martin Sheen', u'Sissy Spacek', u'Warren Oa..."
495,7.8,The Day of the Jackal,PG,Crime,143,"[u'Edward Fox', u'Terence Alexander', u'Michel..."

In [48]:
df.loc[(df['genre']=='Crime')|(df['content_rating']=='PG')] # Or will consider either of one condition needs to be true

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
...,...,...,...,...,...,...
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [4]:
df.loc[(df['star_rating']<9.0)&(df['star_rating']>8)]

,star_rating,title,content_rating,genre,duration,actors_list
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
...,...,...,...,...,...,...
292,8.1,The Manchurian Candidate,APPROVED,Mystery,126,"[u'Frank Sinatra', u'Laurence Harvey', u'Janet..."
293,8.1,Duck Soup,PASSED,Comedy,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
294,8.1,Beauty and the Beast,G,Animation,84,"[u""Paige O'Hara"", u'Robby Benson', u'Richard W..."
295,8.1,The Truman Show,PG,Drama,103,"[u'Jim Carrey', u'Ed Harris', u'Laura Linney']"
296,8.1,The Wild Bunch,R,Action,145,"[u'William Holden', u'Ernest Borgnine', u'Robe..."

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/movies_data.csv")
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [10]:
df.loc[(df['content_rating']=='R')&(df['star_rating']>=9.0)]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."

In [8]:
df.loc[~((df['star_rating']<=9.0)&(df['star_rating']>=8))] # ~ not equals to

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
394,7.9,Birdman: Or (The Unexpected Virtue of Ignorance),R,Comedy,119,"[u'Michael Keaton', u'Zach Galifianakis', u'Ed..."
395,7.9,Big Hero 6,PG,Animation,102,"[u'Ryan Potter', u'Scott Adsit', u'Jamie Chung']"
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [13]:
df.loc[(df['genre']=="Action")|(df['star_rating']<7)]

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
...,...,...,...,...,...,...
918,7.5,Running Scared,R,Action,122,"[u'Paul Walker', u'Cameron Bright', u'Chazz Pa..."
954,7.4,X-Men,PG-13,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [15]:
df.loc[(df['genre']=="Action")|(df["star_rating"]>=7)]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."