## Group by functions

In [2]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Jai', 'Anuj', 'Jai', 'Princi', 'Gaurav', 'Anuj', 'Princi', 'Abhi', 'Anuj'],
    'Age': [27, 24, 22, 32, 33, 29, 27, 32, 32],
    'Address': ['Nagpur', 'Pune', 'Kanpur', 'Allahabad', 'Jodhpur', 'Kanpur', 'Allahabad', 'Aligarh', 'Pune'],
    'Qualification': ['Msc', 'MA', 'MCA', 'PHD', 'BE', 'B.com', 'Msc', 'MA', 'B.com'],
    'Score': [24, 24, 35, 45, 53, 47, 50, 52, 60]
}

df = pd.DataFrame(data)
df

     Name  Age    Address Qualification  Score
0     Jai   27     Nagpur           Msc     24
1    Anuj   24       Pune            MA     24
2     Jai   22     Kanpur           MCA     35
3  Princi   32  Allahabad           PHD     45
4  Gaurav   33    Jodhpur            BE     53
5    Anuj   29     Kanpur         B.com     47
6  Princi   27  Allahabad           Msc     50
7    Abhi   32    Aligarh            MA     52
8    Anuj   32       Pune         B.com     60

In [30]:
# Q: Write a code to get the avg score for different degrees
df.groupby(['Qualification'])['Score'].agg(np.mean)

<ipython-input-30-2db03d9d68c7>:2: FutureWarning: The provided callable <function mean at 0x7817b2da6340> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(['Qualification'])['Score'].agg(np.mean)

Qualification
B.com    53.5
BE       53.0
MA       38.0
MCA      35.0
Msc      37.0
PHD      45.0
Name: Score, dtype: float64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           9 non-null      object
 1   Age            9 non-null      int64
 2   Address        9 non-null      object
 3   Qualification  9 non-null      object
 4   Score          9 non-null      int64
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes

## Get_group

In [3]:
### Groups

df.groupby('Name').groups

{'Abhi': [7], 'Anuj': [1, 5, 8], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}

In [4]:
df.groupby('Address').groups

{'Aligarh': [7], 'Allahabad': [3, 6], 'Jodhpur': [4], 'Kanpur': [2, 5], 'Nagpur': [0], 'Pune': [1, 8]}

In [5]:
### ngroups --> it will return the number of unique values

df.groupby('Address').ngroups

6

## Size in groupby

In [6]:
df.groupby('Name').size()

Name
Abhi      1
Anuj      3
Gaurav    1
Jai       2
Princi    2
dtype: int64

## Sort in groupby

In [ ]:
# group by is by default sorted

In [7]:
df.groupby(['Score'], sort=True).mean('Age')

        Age
Score
24     25.5
35     22.0
45     32.0
47     29.0
50     27.0
52     32.0
53     33.0
60     32.0

In [8]:
df.groupby(['Score'], sort=False).mean('Age')

        Age
Score
24     25.5
35     22.0
45     32.0
53     33.0
47     29.0
50     27.0
52     32.0
60     32.0

## Statistical Functions on groupby

In [ ]:
# Given a dataset, give avg age of students

In [12]:
df.groupby(['Name'], sort=False).mean('Age') #avg/mean

              Age      Score
Name
Jai     24.500000  29.500000
Anuj    28.333333  43.666667
Princi  29.500000  47.500000
Gaurav  33.000000  53.000000
Abhi    32.000000  52.000000

In [15]:
df.groupby(['Name'], sort=False).median('Age')

         Age  Score
Name
Jai     24.5   29.5
Anuj    29.0   47.0
Princi  29.5   47.5
Gaurav  33.0   53.0
Abhi    32.0   52.0

In [16]:
df.groupby(['Name'], sort=False).median('Age').reset_index()

     Name   Age  Score
0     Jai  24.5   29.5
1    Anuj  29.0   47.0
2  Princi  29.5   47.5
3  Gaurav  33.0   53.0
4    Abhi  32.0   52.0

In [18]:
df.groupby(['Name'], sort=False)['Age'].sum().reset_index()

     Name  Age
0     Jai   49
1    Anuj   85
2  Princi   59
3  Gaurav   33
4    Abhi   32

In [19]:
df.groupby(['Name'], sort=False)['Age'].min().reset_index()

     Name  Age
0     Jai   22
1    Anuj   24
2  Princi   27
3  Gaurav   33
4    Abhi   32

In [20]:
df.groupby(['Name'], sort=False)['Age'].max().reset_index()

     Name  Age
0     Jai   27
1    Anuj   32
2  Princi   32
3  Gaurav   33
4    Abhi   32

In [21]:
df.groupby(['Name'], sort=False)['Age'].count().reset_index()

     Name  Age
0     Jai    2
1    Anuj    3
2  Princi    2
3  Gaurav    1
4    Abhi    1

## Agg functions in groupby

In [24]:
df.groupby(['Name'])['Age'].agg(np.sum)

<ipython-input-24-6698e60e4f4c>:1: FutureWarning: The provided callable <function sum at 0x7817b2da5260> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(['Name'])['Age'].agg(np.sum)

Name
Abhi      32
Anuj      85
Gaurav    33
Jai       49
Princi    59
Name: Age, dtype: int64

In [25]:
df.groupby(['Name'])['Age'].agg([np.sum, np.mean, np.median, np.std])

<ipython-input-25-8df022006204>:1: FutureWarning: The provided callable <function sum at 0x7817b2da5260> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(['Name'])['Age'].agg([np.sum, np.mean, np.median, np.std])
<ipython-input-25-8df022006204>:1: FutureWarning: The provided callable <function mean at 0x7817b2da6340> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(['Name'])['Age'].agg([np.sum, np.mean, np.median, np.std])
<ipython-input-25-8df022006204>:1: FutureWarning: The provided callable <function median at 0x7817afb23600> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby(['Name'])['Age'].agg([np.sum, np.mean, np.median, np.std])
<ipython-input-25-8df022006204>:1: FutureWarning: The provided callable <function std at 0x7817b2da6480> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  df.groupby(['Name'])['Age'].agg([np.sum, np.mean, np.median, np.std])

        sum       mean  median       std
Name
Abhi     32  32.000000    32.0       NaN
Anuj     85  28.333333    29.0  4.041452
Gaurav   33  33.000000    33.0       NaN
Jai      49  24.500000    24.5  3.535534
Princi   59  29.500000    29.5  3.535534

## Aggregate function in groupby

In [26]:
df.groupby(['Name', 'Qualification']).aggregate(np.sum)

<ipython-input-26-a824b1c7bbfb>:1: FutureWarning: The provided callable <function sum at 0x7817b2da5260> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(['Name', 'Qualification']).aggregate(np.sum)

                      Age     Address  Score
Name   Qualification
Abhi   MA              32     Aligarh     52
Anuj   B.com           61  KanpurPune    107
       MA              24        Pune     24
Gaurav BE              33     Jodhpur     53
Jai    MCA             22      Kanpur     35
       Msc             27      Nagpur     24
Princi Msc             27   Allahabad     50
       PHD             32   Allahabad     45

In [27]:
df.groupby(['Name', 'Qualification']).aggregate(np.sum).reset_index()

<ipython-input-27-e45f27edc298>:1: FutureWarning: The provided callable <function sum at 0x7817b2da5260> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby(['Name', 'Qualification']).aggregate(np.sum).reset_index()

     Name Qualification  Age     Address  Score
0    Abhi            MA   32     Aligarh     52
1    Anuj         B.com   61  KanpurPune    107
2    Anuj            MA   24        Pune     24
3  Gaurav            BE   33     Jodhpur     53
4     Jai           MCA   22      Kanpur     35
5     Jai           Msc   27      Nagpur     24
6  Princi           Msc   27   Allahabad     50
7  Princi           PHD   32   Allahabad     45

## Apply

In [31]:
df

     Name  Age    Address Qualification  Score
0     Jai   27     Nagpur           Msc     24
1    Anuj   24       Pune            MA     24
2     Jai   22     Kanpur           MCA     35
3  Princi   32  Allahabad           PHD     45
4  Gaurav   33    Jodhpur            BE     53
5    Anuj   29     Kanpur         B.com     47
6  Princi   27  Allahabad           Msc     50
7    Abhi   32    Aligarh            MA     52
8    Anuj   32       Pune         B.com     60

In [33]:
def addition(var):
  return var + 2

addition(2)

df['Age'] = df['Age'].apply(addition)
df

     Name  Age    Address Qualification  Score
0     Jai   29     Nagpur           Msc     24
1    Anuj   26       Pune            MA     24
2     Jai   24     Kanpur           MCA     35
3  Princi   34  Allahabad           PHD     45
4  Gaurav   35    Jodhpur            BE     53
5    Anuj   31     Kanpur         B.com     47
6  Princi   29  Allahabad           Msc     50
7    Abhi   34    Aligarh            MA     52
8    Anuj   34       Pune         B.com     60

In [35]:
def uppercase(var):
  return var.upper()

uppercase("India")


df['Qualification'] = df['Qualification'].apply(uppercase)
df

     Name  Age    Address Qualification  Score
0     Jai   29     Nagpur           MSC     24
1    Anuj   26       Pune            MA     24
2     Jai   24     Kanpur           MCA     35
3  Princi   34  Allahabad           PHD     45
4  Gaurav   35    Jodhpur            BE     53
5    Anuj   31     Kanpur         B.COM     47
6  Princi   29  Allahabad           MSC     50
7    Abhi   34    Aligarh            MA     52
8    Anuj   34       Pune         B.COM     60

In [42]:
# def swapcase1(var):
#   return var.swapcase()

def get_power(var):
  return np.square(var)

get_power(3)
# df['Name'] = df['Name'].apply(swapcase1)
# df

df['Score'] = df['Score'].apply(get_power)
df

     Name  Age    Address Qualification  Score
0     Jai   29     Nagpur           MSC    576
1    Anuj   26       Pune            MA    576
2     Jai   24     Kanpur           MCA   1225
3  Princi   34  Allahabad           PHD   2025
4  Gaurav   35    Jodhpur            BE   2809
5    Anuj   31     Kanpur         B.COM   2209
6  Princi   29  Allahabad           MSC   2500
7    Abhi   34    Aligarh            MA   2704
8    Anuj   34       Pune         B.COM   3600

## Apply function with Lambda