In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Gender       891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.Gender.unique()

array(['male', 'female'], dtype=object)

In [5]:
df.Gender.value_counts()

Gender
male      577
female    314
Name: count, dtype: int64

In [11]:
df.loc[(df.Gender == 'male')&(df['Survived']==1)]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,13,1,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
16,17,1,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [15]:
df.loc[(df.Gender == 'male')&(df['Survived']==0)].shape[0]

465

In [14]:
df.loc[(df.Gender == 'female')&(df['Survived']==0)]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
854,855,0,2,"Carter, Mrs. Ernest Courtenay (Lilian Hughes)",female,44.0,1,0,244252,26.0000,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

## Dtype function

In [18]:
df.Gender.dtype

dtype('O')

In [22]:
df.Survived.dtype

dtype('float64')

## Astype function

In [20]:
df.Survived = df.Survived.astype('float')

In [21]:
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0.0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1.0,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0.0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1.0,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0.0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
dft = pd.DataFrame({'A': np.random.randint(10, 20, 5), 'B': [10, 20, 30, 40, 50]})
dft

    A   B
0  11  10
1  12  20
2  15  30
3  18  40
4  11  50

In [24]:
dft['C'] = 'GENAI'
dft

    A   B      C
0  11  10  GENAI
1  12  20  GENAI
2  15  30  GENAI
3  18  40  GENAI
4  11  50  GENAI

In [25]:
dft['D'] = dft['A'] + dft['B']
dft

    A   B      C   D
0  11  10  GENAI  21
1  12  20  GENAI  32
2  15  30  GENAI  45
3  18  40  GENAI  58
4  11  50  GENAI  61

In [27]:
dft['D'] = dft['D'].astype('str')
dft['D'].dtype

dtype('O')

In [28]:
dft['D'] = dft['D'] + '%'
dft

    A   B      C    D
0  11  10  GENAI  21%
1  12  20  GENAI  32%
2  15  30  GENAI  45%
3  18  40  GENAI  58%
4  11  50  GENAI  61%

## Insert()

In [29]:
# syntax :
# df.insert(location_index, column_name, column_values)

In [30]:
dft

    A   B      C    D
0  11  10  GENAI  21%
1  12  20  GENAI  32%
2  15  30  GENAI  45%
3  18  40  GENAI  58%
4  11  50  GENAI  61%

In [31]:
dft.insert(1, 'X', [-11, -22, -33, -44, -55])
dft

    A   X   B      C    D
0  11 -11  10  GENAI  21%
1  12 -22  20  GENAI  32%
2  15 -33  30  GENAI  45%
3  18 -44  40  GENAI  58%
4  11 -55  50  GENAI  61%

In [32]:
dft.insert(5, 'Z', 10000)
dft

    A   X   B      C    D      Z
0  11 -11  10  GENAI  21%  10000
1  12 -22  20  GENAI  32%  10000
2  15 -33  30  GENAI  45%  10000
3  18 -44  40  GENAI  58%  10000
4  11 -55  50  GENAI  61%  10000

In [33]:
dft.insert(1,'V',11)
dft

    A   V   X   B      C    D      Z
0  11  11 -11  10  GENAI  21%  10000
1  12  11 -22  20  GENAI  32%  10000
2  15  11 -33  30  GENAI  45%  10000
3  18  11 -44  40  GENAI  58%  10000
4  11  11 -55  50  GENAI  61%  10000

## Arranging Rows and Columns as per need

In [34]:
dft[['A', 'B', 'C', 'D', 'V', 'X', 'Z']]

    A   B      C    D   V   X      Z
0  11  10  GENAI  21%  11 -11  10000
1  12  20  GENAI  32%  11 -22  10000
2  15  30  GENAI  45%  11 -33  10000
3  18  40  GENAI  58%  11 -44  10000
4  11  50  GENAI  61%  11 -55  10000

In [38]:
df = dft.T
df

       0      1      2      3      4
A     11     12     15     18     11
V     11     11     11     11     11
X    -11    -22    -33    -44    -55
B     10     20     30     40     50
C  GENAI  GENAI  GENAI  GENAI  GENAI
D    21%    32%    45%    58%    61%
Z  10000  10000  10000  10000  10000

In [41]:
df1 = df[[2, 0, 1, 3, 4]].T

In [42]:
df1

    A   V    X   B      C    D      Z
2  15  11  -33  30  GENAI  45%  10000
0  11  11  -11  10  GENAI  21%  10000
1  12  11  -22  20  GENAI  32%  10000
3  18  11  -44  40  GENAI  58%  10000
4  11  11  -55  50  GENAI  61%  10000

In [48]:
df1.insert(1,'P1',[7,7,8,8,9]) # We need same column length
df1

    A  P1  P   V    X   B      C    D      Z
2  15   7  7  11  -33  30  GENAI  45%  10000
0  11   7  7  11  -11  10  GENAI  21%  10000
1  12   8  8  11  -22  20  GENAI  32%  10000
3  18   8  8  11  -44  40  GENAI  58%  10000
4  11   9  9  11  -55  50  GENAI  61%  10000

In [50]:
df1.insert(18,'P2',[7,7,8,8,9]) # We need same column length
df1

IndexError: index 18 is out of bounds for axis 0 with size 9

## Re-Name

In [52]:
dfx = df.T
dfx

    A   V    X   B      C    D      Z
0  11  11  -11  10  GENAI  21%  10000
1  12  11  -22  20  GENAI  32%  10000
2  15  11  -33  30  GENAI  45%  10000
3  18  11  -44  40  GENAI  58%  10000
4  11  11  -55  50  GENAI  61%  10000

In [55]:
dfx.rename(columns={'A':'a'}, inplace=True)
dfx

    a   V    X   B      C    D      Z
0  11  11  -11  10  GENAI  21%  10000
1  12  11  -22  20  GENAI  32%  10000
2  15  11  -33  30  GENAI  45%  10000
3  18  11  -44  40  GENAI  58%  10000
4  11  11  -55  50  GENAI  61%  10000

In [56]:
dfx.rename({'V':'Virat'}, inplace=True, axis=1)
dfx

    a Virat    X   B      C    D      Z
0  11    11  -11  10  GENAI  21%  10000
1  12    11  -22  20  GENAI  32%  10000
2  15    11  -33  30  GENAI  45%  10000
3  18    11  -44  40  GENAI  58%  10000
4  11    11  -55  50  GENAI  61%  10000

In [58]:
dfx.rename({0:'Movie',1:'simran', 2:'raj', 3:'Heer', 4:'Ranjha'}, inplace=True, axis=0)
dfx

         a Virat    X   B      C    D      Z
Movie   11    11  -11  10  GENAI  21%  10000
simran  12    11  -22  20  GENAI  32%  10000
raj     15    11  -33  30  GENAI  45%  10000
Heer    18    11  -44  40  GENAI  58%  10000
Ranjha  11    11  -55  50  GENAI  61%  10000

In [61]:
dfx.rename({"Movie":'₹'},inplace= True,axis=0)

In [62]:
dfx

         a Virat    X   B      C    D      Z
₹       11    11  -11  10  GENAI  21%  10000
simran  12    11  -22  20  GENAI  32%  10000
raj     15    11  -33  30  GENAI  45%  10000
Heer    18    11  -44  40  GENAI  58%  10000
Ranjha  11    11  -55  50  GENAI  61%  10000

In [66]:
dfx

         a Virat    X   B      C    D      Z
₹       11    11  -11  10  GENAI  21%  10000
simran  12    11  -22  20  GENAI  32%  10000
raj     15    11  -33  30  GENAI  45%  10000
Heer    18    11  -44  40  GENAI  58%  10000
Ranjha  11    11  -55  50  GENAI  61%  10000

In [65]:
df5 = dfx.rename({"₹":'₹1vn'},inplace=False,axis=0)
df5

         a Virat    X   B      C    D      Z
₹1vn    11    11  -11  10  GENAI  21%  10000
simran  12    11  -22  20  GENAI  32%  10000
raj     15    11  -33  30  GENAI  45%  10000
Heer    18    11  -44  40  GENAI  58%  10000
Ranjha  11    11  -55  50  GENAI  61%  10000