In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_excel("/content/Top 1%.xlsx")
df

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# detecting null values
df.isnull()
df.isna()
df.isnull().sum()
df.isna().sum()

# filling null values
df.fillna() #mean(), median(), text, random values, zeros, ones, etc

# Dropping null values
df.dropna() # Threshhold, subset, column/rows (axis = 1/0)
df.drop() # Row wise of column wise it drops the items

In [4]:
# df.dropna()

df1 = df.dropna()
df1

Empty DataFrame
Columns: [date_of_expense, card_name, month, spender, Expense, cashback_amt, Cashback, Purpose , Unnamed: 8, Need & wants]
Index: []

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date_of_expense  98 non-null     datetime64[ns]
 1   card_name        98 non-null     object
 2   month            106 non-null    object
 3   spender          46 non-null     object
 4   Expense          98 non-null     float64
 5   cashback_amt     5 non-null      float64
 6   Cashback         7 non-null      float64
 7   Purpose          98 non-null     object
 8   Unnamed: 8       9 non-null      object
 9   Need & wants     33 non-null     object
dtypes: datetime64[ns](1), float64(3), object(6)
memory usage: 8.4+ KB

In [7]:
df3 = df.dropna(thresh=5) #default values as columns
df3

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
93,2025-05-26,Jupiter,may,sumedhh,60.0,NaN,NaN,Bread,NaN,Want
94,2025-05-27,UPI,may,sumedhh,1023.0,NaN,NaN,Rajni,NaN,Want
95,2025-05-27,SBI CC,may,vivekk,230.0,NaN,NaN,Swiggy,NaN,NaN
96,2025-05-28,airtel axis,may,sumedhh,877.0,NaN,NaN,gas ⛽️,NaN,Need
97,2025-05-28,UPI,may,sumedhh,654.0,NaN,NaN,KFC,NaN,Want

In [9]:
df4 = df.dropna(thresh=40)
df4

Empty DataFrame
Columns: [date_of_expense, card_name, month, spender, Expense, cashback_amt, Cashback, Purpose , Unnamed: 8, Need & wants]
Index: []

In [11]:
df.head().dropna() #Default is columns

Empty DataFrame
Columns: [date_of_expense, card_name, month, spender, Expense, cashback_amt, Cashback, Purpose , Unnamed: 8, Need & wants]
Index: []

In [13]:
df5 = df.dropna(thresh=44)
df5

Empty DataFrame
Columns: [date_of_expense, card_name, month, spender, Expense, cashback_amt, Cashback, Purpose , Unnamed: 8, Need & wants]
Index: []

In [17]:
df6 = df.dropna(thresh=7, axis=0) # Rows
df6

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
5,2025-04-26,Airtel Axis,apr,sumedhh,1137.0,NaN,10.00,Grocery,NaN,NaN
6,2025-04-26,Tata neu,apr,sumedhh,2947.0,NaN,7.00,Grocery,NaN,NaN
8,2025-04-27,Tata neu,apr,sumedhh,2047.0,150.0,7.00,grocery,NaN,NaN
9,2025-04-27,sbi-cashback,apr,vivekk,4139.0,NaN,NaN,IIT,clear,NaN
10,2025-04-27,Tata neu,apr,vivekk,297.0,1.0,NaN,Med upi,clear,NaN
11,2025-04-27,sbi-cashback,apr,vivekk,-395.0,NaN,NaN,flipkart,clear,NaN
15,2025-04-30,Airtel Axis,apr,vivekk,249.0,NaN,NaN,Mobile recharge,clear,NaN
18,2025-05-01,SBI Cashback,may,vivekk,901.0,NaN,5.00,amz,NaN,NaN
19,2025-05-01,SBI cashback,may,vivekk,664.0,NaN,5.00,flipkart,refund,NaN
42,2025-05-09,SBI cashback,may,vivekk,3880.0,-100.0,NaN,lightbill,-84 checkpoint,NaN
47,2025-05-11,SBI cashback,may,vivekk,2613.0,NaN,NaN,lightbill,16 checkpoint,Need
65,2025-05-19,UPI,may,Bobby,1200.0,NaN,NaN,Lend,(check for repayment),NaN
68,2025-05-19,sbi-cashback,may,vivekk,181.0,NaN,NaN,lights,NaN,Want
69,2025-05-19,Jupiter,may,vivekk,5000.0,NaN,NaN,gym fees,NaN,Need
76,2025-05-22,UPI,may,vivekk,20000.0,NaN,NaN,UPI,NaN,Need
79,2025-05-23,SBI CC,may,vivekk,499.0,NaN,NaN,Ring light,NaN,Want
80,2025-05-23,SBI CC,may,vivekk,1011.0,NaN,NaN,Gas Bill,NaN,Need
81,2025-05-23,UPI,may,vivekk,-20000.0,NaN,NaN,Paid back,NaN,Need
89,2025-05-25,UPI,may,sumedhh,-41000.0,NaN,NaN,macbook sold,NaN,Need
90,2025-05-26,SBI CC,may,vivekk,248.0,NaN,NaN,Zomato,NaN,Want
91,2025-05-26,axis iocl,may,sumedhh,160.0,NaN,NaN,petrol,NaN,Want
92,2025-05-26,Axis iocl,may,sumedhh,40.0,NaN,NaN,Flowers,NaN,Want
93,2025-05-26,Jupiter,may,sumedhh,60.0,NaN,NaN,Bread,NaN,Want
94,2025-05-27,UPI,may,sumedhh,1023.0,NaN,NaN,Rajni,NaN,Want
96,2025-05-28,airtel axis,may,sumedhh,877.0,NaN,NaN,gas ⛽️,NaN,Need
97,2025-05-28,UPI,may,sumedhh,654.0,NaN,NaN,KFC,NaN,Want

In [20]:
df7 = df.dropna(thresh=3, axis=0) # Rows
df7

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
93,2025-05-26,Jupiter,may,sumedhh,60.0,NaN,NaN,Bread,NaN,Want
94,2025-05-27,UPI,may,sumedhh,1023.0,NaN,NaN,Rajni,NaN,Want
95,2025-05-27,SBI CC,may,vivekk,230.0,NaN,NaN,Swiggy,NaN,NaN
96,2025-05-28,airtel axis,may,sumedhh,877.0,NaN,NaN,gas ⛽️,NaN,Need
97,2025-05-28,UPI,may,sumedhh,654.0,NaN,NaN,KFC,NaN,Want

In [21]:
df

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df7 = df.dropna(thresh=2, axis=0) # Rows
df7

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

### Subset
- Drop null values for specific to any column or rows

In [27]:
df.dropna(subset=['Cashback'])

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
5,2025-04-26,Airtel Axis,apr,sumedhh,1137.0,NaN,10.00,Grocery,NaN,NaN
6,2025-04-26,Tata neu,apr,sumedhh,2947.0,NaN,7.00,Grocery,NaN,NaN
8,2025-04-27,Tata neu,apr,sumedhh,2047.0,150.0,7.00,grocery,NaN,NaN
18,2025-05-01,SBI Cashback,may,vivekk,901.0,NaN,5.00,amz,NaN,NaN
19,2025-05-01,SBI cashback,may,vivekk,664.0,NaN,5.00,flipkart,refund,NaN

In [28]:
df.dropna(subset=['Unnamed: 8'])

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.0,Swiggy,clear,NaN
9,2025-04-27,sbi-cashback,apr,vivekk,4139.0,NaN,NaN,IIT,clear,NaN
10,2025-04-27,Tata neu,apr,vivekk,297.0,1.0,NaN,Med upi,clear,NaN
11,2025-04-27,sbi-cashback,apr,vivekk,-395.0,NaN,NaN,flipkart,clear,NaN
15,2025-04-30,Airtel Axis,apr,vivekk,249.0,NaN,NaN,Mobile recharge,clear,NaN
19,2025-05-01,SBI cashback,may,vivekk,664.0,NaN,5.0,flipkart,refund,NaN
42,2025-05-09,SBI cashback,may,vivekk,3880.0,-100.0,NaN,lightbill,-84 checkpoint,NaN
47,2025-05-11,SBI cashback,may,vivekk,2613.0,NaN,NaN,lightbill,16 checkpoint,Need
65,2025-05-19,UPI,may,Bobby,1200.0,NaN,NaN,Lend,(check for repayment),NaN

In [29]:
df.dropna(subset=['card_name', 'month'])

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
93,2025-05-26,Jupiter,may,sumedhh,60.0,NaN,NaN,Bread,NaN,Want
94,2025-05-27,UPI,may,sumedhh,1023.0,NaN,NaN,Rajni,NaN,Want
95,2025-05-27,SBI CC,may,vivekk,230.0,NaN,NaN,Swiggy,NaN,NaN
96,2025-05-28,airtel axis,may,sumedhh,877.0,NaN,NaN,gas ⛽️,NaN,Need
97,2025-05-28,UPI,may,sumedhh,654.0,NaN,NaN,KFC,NaN,Want

In [31]:
df.dropna(subset=['card_name', 'month'], how='any', axis=0)
# df + fun + fun2 + column names         + Kaise?   + kya delete karna hai?

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
93,2025-05-26,Jupiter,may,sumedhh,60.0,NaN,NaN,Bread,NaN,Want
94,2025-05-27,UPI,may,sumedhh,1023.0,NaN,NaN,Rajni,NaN,Want
95,2025-05-27,SBI CC,may,vivekk,230.0,NaN,NaN,Swiggy,NaN,NaN
96,2025-05-28,airtel axis,may,sumedhh,877.0,NaN,NaN,gas ⛽️,NaN,Need
97,2025-05-28,UPI,may,sumedhh,654.0,NaN,NaN,KFC,NaN,Want

In [32]:
df.dropna(subset=['card_name', 'month'], how='all', axis=0)

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dropna --> delete columns / rows
# dropna(thresh=7, axis=0/1)
# dropna(subset=['column names'], how='any/all', axis=1/0)

### DROP

In [39]:
# We can directly drop the column

In [34]:
df

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df.drop(['spender'], axis=1, inplace=True)

In [38]:
df

,date_of_expense,card_name,month,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df.drop(['month'], axis=1, inplace=True)

In [41]:
df

,date_of_expense,card_name,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...
101,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df.drop(['Expense'], axis=1, inplace=True)
df

,date_of_expense,card_name,cashback_amt,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,10.0,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,-240.0,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,NaN,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...
101,NaT,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,NaN,NaN,NaN,NaN

In [51]:
df.drop(1, axis=0, inplace=True)
df

,date_of_expense,card_name,cashback_amt,Purpose,Unnamed: 8,Need & wants
2,2025-04-26,Tata neu,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,NaN,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,NaN,Lasur Jatra,NaN,NaN
5,2025-04-26,Airtel Axis,NaN,Grocery,NaN,NaN
6,2025-04-26,Tata neu,NaN,Grocery,NaN,NaN
...,...,...,...,...,...,...
101,NaT,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,NaN,NaN,NaN,NaN

In [52]:
df.drop(2, axis=0, inplace=True)
df

,date_of_expense,card_name,cashback_amt,Purpose,Unnamed: 8,Need & wants
3,2025-04-26,Airtel axis,NaN,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,NaN,Lasur Jatra,NaN,NaN
5,2025-04-26,Airtel Axis,NaN,Grocery,NaN,NaN
6,2025-04-26,Tata neu,NaN,Grocery,NaN,NaN
7,2025-04-26,Bank upi,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...
101,NaT,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,NaN,NaN,NaN,NaN