In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/ai_dev_productivity.csv")
df

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1
...,...,...,...,...,...,...,...,...,...
495,6.08,594,1,5.3,3,0,0.91,6.8,1
496,2.93,382,2,6.7,3,2,1.38,5.9,0
497,4.62,494,4,7.5,2,0,0.41,4.5,1
498,3.25,296,6,6.9,1,0,1.52,6.3,0
499,2.23,252,4,8.8,0,0,1.05,2.6,0

In [4]:
df.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hours_coding      500 non-null    float64
 1   coffee_intake_mg  500 non-null    int64
 2   distractions      500 non-null    int64
 3   sleep_hours       500 non-null    float64
 4   commits           500 non-null    int64
 5   bugs_reported     500 non-null    int64
 6   ai_usage_hours    500 non-null    float64
 7   cognitive_load    500 non-null    float64
 8   task_success      500 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [6]:
df.isna()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

In [7]:
df.isna().sum()

hours_coding        0
coffee_intake_mg    0
distractions        0
sleep_hours         0
commits             0
bugs_reported       0
ai_usage_hours      0
cognitive_load      0
task_success        0
dtype: int64

In [8]:
df1 = pd.read_excel("/content/Top 1%.xlsx")
df1

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df1.isna()

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,True,False,True,True
2,False,False,False,False,False,True,True,False,True,False
3,False,False,False,False,False,True,False,False,False,True
4,False,False,False,False,False,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...
101,True,True,False,False,True,True,True,True,True,True
102,True,True,False,False,True,True,True,True,True,True
103,True,True,False,False,True,True,True,True,True,True
104,True,True,False,False,True,True,True,True,True,True
105,True,True,False,False,True,True,True,True,True,True

In [10]:
df1.isna().sum()

date_of_expense      8
card_name            8
month                0
spender             60
Expense              8
cashback_amt       101
Cashback            99
Purpose              8
Unnamed: 8          97
Need & wants        73
dtype: int64

In [11]:
df1['Expense'].isna().sum()

np.int64(8)

In [12]:
df1.isnull()

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,True,False,True,True
2,False,False,False,False,False,True,True,False,True,False
3,False,False,False,False,False,True,False,False,False,True
4,False,False,False,False,False,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...
101,True,True,False,False,True,True,True,True,True,True
102,True,True,False,False,True,True,True,True,True,True
103,True,True,False,False,True,True,True,True,True,True
104,True,True,False,False,True,True,True,True,True,True
105,True,True,False,False,True,True,True,True,True,True

In [13]:
df1.isnull().sum()

date_of_expense      8
card_name            8
month                0
spender             60
Expense              8
cashback_amt       101
Cashback            99
Purpose              8
Unnamed: 8          97
Need & wants        73
dtype: int64

In [14]:
df1['Expense'].isnull().sum()

np.int64(8)

In [16]:
df.describe().loc['mean']

hours_coding          5.01560
coffee_intake_mg    463.19200
distractions          2.97600
sleep_hours           6.97580
commits               4.60800
bugs_reported         0.85800
ai_usage_hours        1.51092
cognitive_load        4.49820
task_success          0.60600
Name: mean, dtype: float64

In [21]:
df.describe().iloc[1]

hours_coding          5.01560
coffee_intake_mg    463.19200
distractions          2.97600
sleep_hours           6.97580
commits               4.60800
bugs_reported         0.85800
ai_usage_hours        1.51092
cognitive_load        4.49820
task_success          0.60600
Name: mean, dtype: float64

In [22]:
df['commits'].mean()

np.float64(4.608)

In [23]:
np.mean(df['commits'])

np.float64(4.608)

In [24]:
df['commits'].median()

5.0

In [25]:
df.median()

hours_coding          5.03
coffee_intake_mg    500.50
distractions          3.00
sleep_hours           6.95
commits               5.00
bugs_reported         0.00
ai_usage_hours        1.26
cognitive_load        4.40
task_success          1.00
dtype: float64

In [26]:
import statistics as st

In [27]:
st.mode(df['commits'])

5

In [28]:
df['commits'].min()

0

In [30]:
np.min(df['commits'])

0

In [29]:
df['commits'].max()

13

In [31]:
np.max(df['commits'])

13

In [32]:
df.sum()

hours_coding          2507.80
coffee_intake_mg    231596.00
distractions          1488.00
sleep_hours           3487.90
commits               2304.00
bugs_reported          429.00
ai_usage_hours         755.46
cognitive_load        2249.10
task_success           303.00
dtype: float64

In [34]:
np.var(df.commits)

7.302335999999997

In [35]:
df.commits.var()

7.3169699398797565

In [ ]:
# EDA = Exploratory Data Analysis

In [ ]:
# Initial Exploration of dataset

In [33]:
df['commits'].sum()

np.int64(2304)

In [36]:
np.sqrt(df.commits)

0      1.414214
1      2.236068
2      1.414214
3      3.000000
4      2.000000
         ...
495    1.732051
496    1.732051
497    1.414214
498    1.000000
499    0.000000
Name: commits, Length: 500, dtype: float64

In [37]:
np.cbrt(df.commits)

0      1.259921
1      1.709976
2      1.259921
3      2.080084
4      1.587401
         ...
495    1.442250
496    1.442250
497    1.259921
498    1.000000
499    0.000000
Name: commits, Length: 500, dtype: float64

In [38]:
np.square(df.commits)

0       4
1      25
2       4
3      81
4      16
       ..
495     9
496     9
497     4
498     1
499     0
Name: commits, Length: 500, dtype: int64

In [41]:
df.commits**3

0        8
1      125
2        8
3      729
4       64
      ...
495     27
496     27
497      8
498      1
499      0
Name: commits, Length: 500, dtype: int64

In [42]:
df

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1
...,...,...,...,...,...,...,...,...,...
495,6.08,594,1,5.3,3,0,0.91,6.8,1
496,2.93,382,2,6.7,3,2,1.38,5.9,0
497,4.62,494,4,7.5,2,0,0.41,4.5,1
498,3.25,296,6,6.9,1,0,1.52,6.3,0
499,2.23,252,4,8.8,0,0,1.05,2.6,0