# Joining the DataFrames

## Append function

- Appending along the rows

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({'ASCII_Num': np.arange(65,71),
                    'char': [chr(i) for i in range(65, 71)]})

df1

   ASCII_Num char
0         65    A
1         66    B
2         67    C
3         68    D
4         69    E
5         70    F

In [3]:
df2 = pd.DataFrame({'ASCII_Num': np.arange(71,76),
                    'char': [chr(i) for i in range(71, 76)]})

df2

   ASCII_Num char
0         71    G
1         72    H
2         73    I
3         74    J
4         75    K

In [4]:
df1.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'

In [16]:
display(df1, df2)

   ASCII_Num char
0         65    A
1         66    B
2         67    C
3         68    D
4         69    E
5         70    F

   ASCII_Num char
0         71    G
1         72    H
2         73    I
3         74    J
4         75    K

## Concat

In [5]:
pd.concat([df1, df2], axis=0)

   ASCII_Num char
0         65    A
1         66    B
2         67    C
3         68    D
4         69    E
5         70    F
0         71    G
1         72    H
2         73    I
3         74    J
4         75    K

In [6]:
pd.concat([df1, df2], axis=0, ignore_index=True)

    ASCII_Num char
0          65    A
1          66    B
2          67    C
3          68    D
4          69    E
5          70    F
6          71    G
7          72    H
8          73    I
9          74    J
10         75    K

In [7]:
df3 = pd.DataFrame({'ASCII_Num': np.arange(71,75),
                    'characters': [chr(i) for i in range(71, 75)]})

df3

   ASCII_Num characters
0         71          G
1         72          H
2         73          I
3         74          J

In [17]:
display(df1, df3)

   ASCII_Num char
0         65    A
1         66    B
2         67    C
3         68    D
4         69    E
5         70    F

   ASCII_Num characters
0         71          G
1         72          H
2         73          I
3         74          J

In [8]:
pd.concat([df1, df3], axis=0, ignore_index=True)

   ASCII_Num char characters
0         65    A        NaN
1         66    B        NaN
2         67    C        NaN
3         68    D        NaN
4         69    E        NaN
5         70    F        NaN
6         71  NaN          G
7         72  NaN          H
8         73  NaN          I
9         74  NaN          J

In [9]:
df4 = pd.DataFrame({'ASCII_Numbers': np.arange(71,75),
                    'characters': [chr(i) for i in range(71, 75)]})

df4

   ASCII_Numbers characters
0             71          G
1             72          H
2             73          I
3             74          J

In [10]:
display(df1, df2, df3, df4)

   ASCII_Num char
0         65    A
1         66    B
2         67    C
3         68    D
4         69    E
5         70    F

   ASCII_Num char
0         71    G
1         72    H
2         73    I
3         74    J
4         75    K

   ASCII_Num characters
0         71          G
1         72          H
2         73          I
3         74          J

   ASCII_Numbers characters
0             71          G
1             72          H
2             73          I
3             74          J

In [11]:
pd.concat([df1, df4], axis=0, ignore_index=True)

   ASCII_Num char  ASCII_Numbers characters
0       65.0    A            NaN        NaN
1       66.0    B            NaN        NaN
2       67.0    C            NaN        NaN
3       68.0    D            NaN        NaN
4       69.0    E            NaN        NaN
5       70.0    F            NaN        NaN
6        NaN  NaN           71.0          G
7        NaN  NaN           72.0          H
8        NaN  NaN           73.0          I
9        NaN  NaN           74.0          J

### Concat along the columns

In [13]:
pd.concat([df1, df2], axis=1)

   ASCII_Num char  ASCII_Num char
0         65    A       71.0    G
1         66    B       72.0    H
2         67    C       73.0    I
3         68    D       74.0    J
4         69    E       75.0    K
5         70    F        NaN  NaN

In [14]:
pd.concat([df1, df3], axis=1)

   ASCII_Num char  ASCII_Num characters
0         65    A       71.0          G
1         66    B       72.0          H
2         67    C       73.0          I
3         68    D       74.0          J
4         69    E        NaN        NaN
5         70    F        NaN        NaN

In [15]:
pd.concat([df1, df4], axis=1)

   ASCII_Num char  ASCII_Numbers characters
0         65    A           71.0          G
1         66    B           72.0          H
2         67    C           73.0          I
3         68    D           74.0          J
4         69    E            NaN        NaN
5         70    F            NaN        NaN

## Join parameters in concat

In [18]:
pd.concat([df1, df4], axis=1, join='inner') # Keeps the common rows only

   ASCII_Num char  ASCII_Numbers characters
0         65    A             71          G
1         66    B             72          H
2         67    C             73          I
3         68    D             74          J

In [19]:
pd.concat([df1, df4], axis=1, join='outer') # Keeps all the common rows

   ASCII_Num char  ASCII_Numbers characters
0         65    A           71.0          G
1         66    B           72.0          H
2         67    C           73.0          I
3         68    D           74.0          J
4         69    E            NaN        NaN
5         70    F            NaN        NaN

In [23]:
pd.concat([df1, df3], axis=0, join='inner') # Keeps the common columns only

   ASCII_Num
0         65
1         66
2         67
3         68
4         69
5         70
0         71
1         72
2         73
3         74

In [24]:
pd.concat([df1, df3], axis=0, join='outer') # Keeps all the common columns

   ASCII_Num char characters
0         65    A        NaN
1         66    B        NaN
2         67    C        NaN
3         68    D        NaN
4         69    E        NaN
5         70    F        NaN
0         71  NaN          G
1         72  NaN          H
2         73  NaN          I
3         74  NaN          J