# Null Values Treatment in PANDAS

## Identify null values

In [1]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_excel('/content/Top 1%.xlsx')
df

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date_of_expense  98 non-null     datetime64[ns]
 1   card_name        98 non-null     object
 2   month            106 non-null    object
 3   spender          46 non-null     object
 4   Expense          98 non-null     float64
 5   cashback_amt     5 non-null      float64
 6   Cashback         7 non-null      float64
 7   Purpose          98 non-null     object
 8   Unnamed: 8       9 non-null      object
 9   Need & wants     33 non-null     object
dtypes: datetime64[ns](1), float64(3), object(6)
memory usage: 8.4+ KB

In [5]:
df['cashback_amt'].isnull().sum()

np.int64(101)

In [9]:
df['spender'].isna().sum()

np.int64(60)

In [6]:
any(df['cashback_amt'].isnull())

True

In [10]:
# how to get to know how may columns are there which has null values ?

df.columns[df.isna().any()]

Index(['date_of_expense', 'card_name', 'spender', 'Expense', 'cashback_amt',
       'Cashback', 'Purpose ', 'Unnamed: 8', 'Need & wants'],
      dtype='object')

In [11]:
# how to check if a column has all null values

df.columns[df.isna().all()]

Index([], dtype='object')

## Treatment

### drop na (delete the null column)

We should use this when a column has all the values as NaN

In [31]:
df1 = df.dropna()
df1

Empty DataFrame
Columns: [date_of_expense, card_name, month, spender, Expense, cashback_amt, Cashback, Purpose , Unnamed: 8, Need & wants]
Index: []

In [15]:
df

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.0,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.0,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.0,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.0,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,NaN,NaN,NaN,NaN,NaN,NaN

Fill the column with some data

In [16]:
df.fillna("AI")

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26 00:00:00,jupiter,apr,sumedhh,495.0,10.0,0.02,Mirchi Red,AI,Need
1,2025-04-26 00:00:00,Axis IOCL,apr,sumedhh,10000.0,-240.0,AI,Ganesh Solat,AI,AI
2,2025-04-26 00:00:00,Tata neu,apr,sumedhh,45.0,AI,AI,upi,AI,Need
3,2025-04-26 00:00:00,Airtel axis,apr,vivekk,1378.0,AI,10.0,Swiggy,clear,AI
4,2025-04-26 00:00:00,Axis Iocl,apr,sumedhh,275.0,AI,AI,Lasur Jatra,AI,AI
...,...,...,...,...,...,...,...,...,...,...
101,AI,AI,may,sumedhh,AI,AI,AI,AI,AI,AI
102,AI,AI,may,sumedhh,AI,AI,AI,AI,AI,AI
103,AI,AI,may,sumedhh,AI,AI,AI,AI,AI,AI
104,AI,AI,may,sumedhh,AI,AI,AI,AI,AI,AI
105,AI,AI,may,sumedhh,AI,AI,AI,AI,AI,AI

Fill na values by columns

In [17]:
# calculate a mean

mean = df['Expense'].mean()
mean

np.float64(1100.8826530612246)

In [18]:
df['Expense'] = df['Expense'].fillna(mean)
df

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.000000,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.000000,-240.0,NaN,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.000000,NaN,NaN,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.000000,NaN,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.000000,NaN,NaN,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,1100.882653,NaN,NaN,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,1100.882653,NaN,NaN,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,1100.882653,NaN,NaN,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,1100.882653,NaN,NaN,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,1100.882653,NaN,NaN,NaN,NaN,NaN

In [19]:
df['Expense'].median()

277.5

In [24]:
df['Cashback'] = df['Cashback'].fillna(df['Cashback'].median())
df

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.000000,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.000000,-240.0,7.00,Ganesh Solat,NaN,NaN
2,2025-04-26,Tata neu,apr,sumedhh,45.000000,277.5,7.00,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.000000,277.5,10.00,Swiggy,clear,NaN
4,2025-04-26,Axis Iocl,apr,sumedhh,275.000000,277.5,7.00,Lasur Jatra,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN

In [25]:
## Backward fill & Forward Fill

In [27]:
df['Need & wants'] = df['Need & wants'].fillna(method='bfill')
df

<ipython-input-27-34599b033f1b>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Need & wants'] = df['Need & wants'].fillna(method='bfill')

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.000000,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.000000,-240.0,7.00,Ganesh Solat,NaN,Need
2,2025-04-26,Tata neu,apr,sumedhh,45.000000,277.5,7.00,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.000000,277.5,10.00,Swiggy,clear,Need
4,2025-04-26,Axis Iocl,apr,sumedhh,275.000000,277.5,7.00,Lasur Jatra,NaN,Need
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
102,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
103,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
104,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN
105,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,NaN

In [28]:
df['Need & wants'] = df['Need & wants'].fillna(method='ffill')
df

<ipython-input-28-37f138efd02f>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Need & wants'] = df['Need & wants'].fillna(method='ffill')

,date_of_expense,card_name,month,spender,Expense,cashback_amt,Cashback,Purpose,Unnamed: 8,Need & wants
0,2025-04-26,jupiter,apr,sumedhh,495.000000,10.0,0.02,Mirchi Red,NaN,Need
1,2025-04-26,Axis IOCL,apr,sumedhh,10000.000000,-240.0,7.00,Ganesh Solat,NaN,Need
2,2025-04-26,Tata neu,apr,sumedhh,45.000000,277.5,7.00,upi,NaN,Need
3,2025-04-26,Airtel axis,apr,vivekk,1378.000000,277.5,10.00,Swiggy,clear,Need
4,2025-04-26,Axis Iocl,apr,sumedhh,275.000000,277.5,7.00,Lasur Jatra,NaN,Need
...,...,...,...,...,...,...,...,...,...,...
101,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,Want
102,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,Want
103,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,Want
104,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,Want
105,NaT,NaN,may,sumedhh,1100.882653,277.5,7.00,NaN,NaN,Want