In [1]:
import numpy as np

In [11]:
array = np.array([2, 3, 4, 6.8, "Ram", "shyam"], dtype='object')
array

array([2, 3, 4, 6.8, 'Ram', 'shyam'], dtype=object)

In [3]:
# Q: Convert any array into a dataframe

In [4]:
import pandas as pd

In [12]:
df = pd.DataFrame(array, columns=['Column 1'])
df

  Column 1
0        2
1        3
2        4
3      6.8
4      Ram
5    shyam

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column 1  6 non-null      object
dtypes: object(1)
memory usage: 180.0+ bytes

In [19]:
list1 = [2, 34, 55, 11]

# change to array

arr = np.array(list1)
print(arr)

# change to dataframe

df = pd.DataFrame(arr, columns=["Values"])
df

[ 2 34 55 11]

   Values
0       2
1      34
2      55
3      11

## Reshape

In [20]:
array = np.array([2, 4, 5, 6, 7, 8, 9, 0 ,0 ,88, 99, 77])
array

array([ 2,  4,  5,  6,  7,  8,  9,  0,  0, 88, 99, 77])

In [23]:
print(array.reshape(1, 12))
print(array.reshape(12, 1))

[[ 2  4  5  6  7  8  9  0  0 88 99 77]]
[[ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [ 0]
 [ 0]
 [88]
 [99]
 [77]]

In [24]:
array.reshape(3, 4)

array([[ 2,  4,  5,  6],
       [ 7,  8,  9,  0],
       [ 0, 88, 99, 77]])

In [25]:
array.reshape(4, 3)

array([[ 2,  4,  5],
       [ 6,  7,  8],
       [ 9,  0,  0],
       [88, 99, 77]])

In [28]:
array.reshape(2, 6)

array([[ 2,  4,  5,  6,  7,  8],
       [ 9,  0,  0, 88, 99, 77]])

In [27]:
array.reshape(6, 2) # 6 lists (each list contains 2 elements)

array([[ 2,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9,  0],
       [ 0, 88],
       [99, 77]])

In [29]:
nums = np.array([2, 3, 4, 5])
nums

array([2, 3, 4, 5])

In [32]:
nums.reshape(2, 2)
# nums.reshape(1, 4)

array([[2, 3],
       [4, 5]])

In [34]:
# 3D examples

In [35]:
array.reshape(2, 3, 2)

array([[[ 2,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9,  0],
        [ 0, 88],
        [99, 77]]])

In [36]:
array.reshape(3, 2, 2)

array([[[ 2,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9,  0]],

       [[ 0, 88],
        [99, 77]]])

In [37]:
array.reshape(2, 2, 3) #(rows, rows, columns)

array([[[ 2,  4,  5],
        [ 6,  7,  8]],

       [[ 9,  0,  0],
        [88, 99, 77]]])

In [41]:
array.reshape(1, 2, 3) # because you had 12 elements in the array, and this is taking only 6 elements

ValueError: cannot reshape array of size 12 into shape (1,2,3)

## tolist
### Converting an Array to a list

In [43]:
list1 = [2, 3, 4, 5]
ary = np.array(list1)
ary

array([2, 3, 4, 5])

In [44]:
# append & extend of lists

In [46]:
list2 = list(ary)
list2.append(100)

list2

[np.int64(2), np.int64(3), np.int64(4), np.int64(5), 100]

In [47]:
X = ary.tolist()
X

[2, 3, 4, 5]

In [48]:
arry = np.array([22, 33, 44, 55])
arry

array([22, 33, 44, 55])

In [51]:
arry.tolist()

[22, 33, 44, 55]