# Random Number Generation

## How to create an empty array

In [1]:
import numpy as np

In [2]:
nums = np.array([2, 3, 4 ,5 ,6])
nums

array([2, 3, 4, 5, 6])

In [3]:
empty_array = np.array([])
empty_array

array([], dtype=float64)

In [62]:
empty_array = np.array([], dtype='int')
empty_array

array([], dtype=int64)

## How to create an array of matrix of zeros

In [64]:
arr = np.zeros(7) #Thala For A Reason
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [9]:
arry = np.zeros(5, dtype='I') # 1D
arry

array([0, 0, 0, 0, 0], dtype=uint32)

In [14]:
arr = np.zeros((5, 4), dtype='I') #2D
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint32)

In [16]:
# Create a matrix of zeros 5 X 9
arr = np.zeros((5, 9), dtype='int')
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
check = np.zeros((4, 10), dtype="str")
check

array([['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [11]:
# What is Dtype

In [ ]:
# Dtype = Data type &
bytes = 8 bytes , 16 bytes, 32 bytes, 64 bytes ---> Mega bytes (10 MB) --> Giga Byte (1 GB) ---> Tera Bytes (TB) ---> Hexa Bytes (HB)

1072 byte ---> 1 MB || 1072 MB --> 1GB

String = str = "Name"
Integer = int = 44 ()
Float = float = 4.9
Boolen = bool = True or False
Complex = complex = 6+0j
Object = object = "Any things"

## How to create a matrix of ones

In [65]:
arr = np.ones(7)
arr

array([1., 1., 1., 1., 1., 1., 1.])

In [67]:
# output = [1, 1, 1, 1, 1]
arr =  np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [26]:
# output = [
#     [1, 1, 1, 1, 1],
#     [1, 1, 1, 1, 1],
#     [1, 1, 1, 1, 1]
# ]
arr =  np.ones((3,5), dtype='int')
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
# Q : Create a DataFrame of ones 10X12 matrix

arr = np.ones((10,12), dtype="I")
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint32)

In [28]:
import pandas as pd

In [35]:
['ABCDEFGHIJKL']

['ABCDEFGHIJKL']

In [33]:
list('ABCDEFGHIJKL')

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']

In [34]:
df = pd.DataFrame(arr, columns=list('ABCDEFGHIJKL')) #80% marks
df

   A  B  C  D  E  F  G  H  I  J  K  L
0  1  1  1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1  1  1  1
2  1  1  1  1  1  1  1  1  1  1  1  1
3  1  1  1  1  1  1  1  1  1  1  1  1
4  1  1  1  1  1  1  1  1  1  1  1  1
5  1  1  1  1  1  1  1  1  1  1  1  1
6  1  1  1  1  1  1  1  1  1  1  1  1
7  1  1  1  1  1  1  1  1  1  1  1  1
8  1  1  1  1  1  1  1  1  1  1  1  1
9  1  1  1  1  1  1  1  1  1  1  1  1

### How to create a sequence of numbers using arange function

In [42]:
range(1, 20)

range(1, 20)

In [48]:
list(range(1, 20))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [46]:
X = list(range(1, 20))
X

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [37]:
range_array = np.arange(1, 20)
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [38]:
list(range(1, 20, 2))  #Mr Mario

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [39]:
range_array = np.arange(1, 20, 2) # Positive step size
range_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
range_array = np.arange(20, 0, -2) # Negative step size
range_array

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### linspace() --> Creates a linear space values

In [47]:
dummy_arr = np.linspace(0, 20)
dummy_arr

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [69]:
dummy_arr = np.linspace(0, 20, num=21, dtype="I")
dummy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=uint32)

In [49]:
dum_arr = np.linspace(0, 23 , 12)
dum_arr

array([ 0.        ,  2.09090909,  4.18181818,  6.27272727,  8.36363636,
       10.45454545, 12.54545455, 14.63636364, 16.72727273, 18.81818182,
       20.90909091, 23.        ])

In [50]:
d_arr = np.linspace(1, 21 , 11)
d_arr

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.])

In [71]:
d_arry = np.linspace(100, 1000, 10) # (start Num, End Num, Numbers of elements)
d_arry

array([ 100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.,
       1000.])

In [58]:
dict1 = {
    'amount': np.linspace(100, 600, 6, dtype = int),
    'interest': np.linspace(12.5, 3.5, 6),
    'month': np.linspace(6, 36, 6, dtype=int)
}
dict1

{'amount': array([100, 200, 300, 400, 500, 600]),
 'interest': array([12.5, 10.7,  8.9,  7.1,  5.3,  3.5]),
 'month': array([ 6, 12, 18, 24, 30, 36])}

In [59]:
df = pd.DataFrame(dict1)
df

   amount  interest  month
0     100      12.5      6
1     200      10.7     12
2     300       8.9     18
3     400       7.1     24
4     500       5.3     30
5     600       3.5     36